var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,h,k){b!=Array.prototype&&b!=Object.prototype&&(b[h]=k.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(b){var h=0;return $jscomp.iteratorPrototype(function(){return h<b.length?{done:!1,value:b[h++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.makeIterator=function(b){$jscomp.initSymbolIterator();var h=b[Symbol.iterator];return h?h.call(b):$jscomp.arrayIterator(b)};
$jscomp.polyfill=function(b,h,k,q){if(h){k=$jscomp.global;b=b.split(".");for(q=0;q<b.length-1;q++){var g=b[q];g in k||(k[g]={});k=k[g]}b=b[b.length-1];q=k[b];h=h(q);h!=q&&null!=h&&$jscomp.defineProperty(k,b,{configurable:!0,writable:!0,value:h})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(b){function h(){this.batch_=null}function k(d){return d instanceof g?d:new g(function(m,b){m(d)})}if(b&&!$jscomp.FORCE_POLYFILL_PROMISE)return b;h.prototype.asyncExecute=function(d){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(d);return this};h.prototype.asyncExecuteBatch_=function(){var d=this;this.asyncExecuteFunction(function(){d.executeBatch_()})};var q=$jscomp.global.setTimeout;h.prototype.asyncExecuteFunction=function(d){q(d,
0)};h.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=this.batch_;this.batch_=[];for(var m=0;m<d.length;++m){var b=d[m];delete d[m];try{b()}catch(x){this.asyncThrow_(x)}}}this.batch_=null};h.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};var g=function(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{d(b.resolve,b.reject)}catch(u){b.reject(u)}};g.prototype.createResolveAndReject_=
function(){function d(d){return function(m){g||(g=!0,d.call(b,m))}}var b=this,g=!1;return{resolve:d(this.resolveTo_),reject:d(this.reject_)}};g.prototype.resolveTo_=function(d){if(d===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof g)this.settleSameAsPromise_(d);else{a:switch(typeof d){case "object":var b=null!=d;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(d):this.fulfill_(d)}};g.prototype.resolveToNonPromiseObj_=function(d){var b=
void 0;try{b=d.then}catch(u){this.reject_(u);return}"function"==typeof b?this.settleSameAsThenable_(b,d):this.fulfill_(d)};g.prototype.reject_=function(d){this.settle_(2,d)};g.prototype.fulfill_=function(d){this.settle_(1,d)};g.prototype.settle_=function(d,b){if(0!=this.state_)throw Error("Cannot settle("+d+", "+b|"): Promise already settled in state"+this.state_);this.state_=d;this.result_=b;this.executeOnSettledCallbacks_()};g.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var d=
this.onSettledCallbacks_,b=0;b<d.length;++b)d[b].call(),d[b]=null;this.onSettledCallbacks_=null}};var l=new h;g.prototype.settleSameAsPromise_=function(d){var b=this.createResolveAndReject_();d.callWhenSettled_(b.resolve,b.reject)};g.prototype.settleSameAsThenable_=function(d,b){var g=this.createResolveAndReject_();try{d.call(b,g.resolve,g.reject)}catch(x){g.reject(x)}};g.prototype.then=function(d,b){function h(d,b){return"function"==typeof d?function(b){try{k(d(b))}catch(t){m(t)}}:b}var k,m,l=new g(function(b,
d){k=b;m=d});this.callWhenSettled_(h(d,k),h(b,m));return l};g.prototype.catch=function(b){return this.then(void 0,b)};g.prototype.callWhenSettled_=function(b,g){function d(){switch(h.state_){case 1:b(h.result_);break;case 2:g(h.result_);break;default:throw Error("Unexpected state: "+h.state_);}}var h=this;null==this.onSettledCallbacks_?l.asyncExecute(d):this.onSettledCallbacks_.push(function(){l.asyncExecute(d)})};g.resolve=k;g.reject=function(b){return new g(function(d,g){g(b)})};g.race=function(b){return new g(function(d,
g){for(var h=$jscomp.makeIterator(b),m=h.next();!m.done;m=h.next())k(m.value).callWhenSettled_(d,g)})};g.all=function(b){var d=$jscomp.makeIterator(b),h=d.next();return h.done?k([]):new g(function(b,g){function m(d){return function(g){l[d]=g;n--;0==n&&b(l)}}var l=[],n=0;do l.push(void 0),n++,k(h.value).callWhenSettled_(m(l.length-1),g),h=d.next();while(!h.done)})};return g},"es6","es3");
(function(b){function h(a,c){function f(){}f.prototype=a;a=new f;for(var b in c)a[b]=c[b];c.toString!==Object.prototype.toString&&(a.toString=c.toString);return a}function k(a,c){if(null==c)return null;null==c.__id__&&(c.__id__=K++);var f;null==a.hx__closures__?a.hx__closures__={}:f=a.hx__closures__[c.__id__];null==f&&(f=function(){return f.method.apply(f.scope,arguments)},f.scope=a,f.method=c,a.hx__closures__[c.__id__]=f);return f}b.xxx=b.xxx||{};var q=function(a,c){this.r=new RegExp(a,c.split("u").join(""))};
q.__name__=!0;q.prototype={match:function(a){this.r.global&&(this.r.lastIndex=0);this.r.m=this.r.exec(a);this.r.s=a;return null!=this.r.m},matched:function(a){if(null!=this.r.m&&0<=a&&a<this.r.m.length)return this.r.m[a];throw new w("EReg::matched");}};var g=function(){};g.__name__=!0;g.cca=function(a,c){a=a.charCodeAt(c);if(a==a)return a};g.substr=function(a,c,f){if(null==f)f=a.length;else if(0>f)if(0==c)f=a.length+f;else return"";return a.substr(c,f)};Math.__name__=!0;var l=function(){};l.__name__=
!0;l.string=function(a){return t.__string_rec(a,"")};l.parseInt=function(a){var c=parseInt(a,10);0!=c||120!=g.cca(a,1)&&88!=g.cca(a,1)||(c=parseInt(a));return isNaN(c)?null:c};var d=function(){};d.__name__=!0;d.isSpace=function(a,c){a=g.cca(a,c);return 8<a&&14>a?!0:32==a};d.ltrim=function(a){for(var c=a.length,f=0;f<c&&d.isSpace(a,f);)++f;return 0<f?g.substr(a,f,c-f):a};d.rtrim=function(a){for(var c=a.length,f=0;f<c&&d.isSpace(a,c-f-1);)++f;return 0<f?g.substr(a,0,c-f):a};d.trim=function(a){return d.ltrim(d.rtrim(a))};
d.replace=function(a,c,f){return a.split(c).join(f)};var m=require("atom").CompositeDisposable,u=require("atom").Emitter,x=require("atom").File,H=require("atom").Point,J=require("atom").Range,z=function(a){var c=this;this.id=setInterval(function(){c.run()},a)};z.__name__=!0;z.delay=function(a,c){var f=new z(c);f.run=function(){f.stop();a()};return f};z.prototype={stop:function(){null!=this.id&&(clearInterval(this.id),this.id=null)},run:function(){}};var n=function(a){switch(a){case ".":case "..":this.dir=
a;this.file="";return}var c=a.lastIndexOf("/"),f=a.lastIndexOf("\\");c<f?(this.dir=g.substr(a,0,f),a=g.substr(a,f+1,null),this.backslash=!0):f<c?(this.dir=g.substr(a,0,c),a=g.substr(a,c+1,null)):this.dir=null;c=a.lastIndexOf(".");-1!=c?(this.ext=g.substr(a,c+1,null),this.file=g.substr(a,0,c)):(this.ext=null,this.file=a)};n.__name__=!0;n.withoutExtension=function(a){a=new n(a);a.ext=null;return a.toString()};n.withoutDirectory=function(a){a=new n(a);a.dir=null;return a.toString()};n.directory=function(a){a=
new n(a);return null==a.dir?"":a.dir};n.extension=function(a){a=new n(a);return null==a.ext?"":a.ext};n.prototype={toString:function(){return(null==this.dir?"":this.dir+(this.backslash?"\\":"/"))+this.file+(null==this.ext?"":"."+this.ext)}};var w=function(a){Error.call(this);this.val=a;this.message=String(a);Error.captureStackTrace&&Error.captureStackTrace(this,w)};w.__name__=!0;w.wrap=function(a){return a instanceof Error?a:new w(a)};w.__super__=Error;w.prototype=h(Error.prototype,{});var t=function(){};
t.__name__=!0;t.__string_rec=function(a,c){if(null==a)return"null";if(5<=c.length)return"<...>";var f=typeof a;"function"==f&&(a.__name__||a.__ename__)&&(f="object");switch(f){case "function":return"<function>";case "object":if(a instanceof Array){if(a.__enum__){if(2==a.length)return a[0];f=a[0]+"(";c+="\t";for(var b=2,d=a.length;b<d;){var e=b++;f=2!=e?f+(","+t.__string_rec(a[e],c)):f+t.__string_rec(a[e],c)}return f+")"}f=a.length;b="[";c+="\t";for(d=0;d<f;)e=d++,b+=(0<e?",":"")+t.__string_rec(a[e],
c);return b+"]"}try{b=a.toString}catch(N){return"???"}if(null!=b&&b!=Object.toString&&"function"==typeof b&&(f=a.toString(),"[object Object]"!=f))return f;f=null;b="{\n";c+="\t";d=null!=a.hasOwnProperty;for(f in a)d&&!a.hasOwnProperty(f)||"prototype"==f||"__class__"==f||"__super__"==f||"__interfaces__"==f||"__properties__"==f||(2!=b.length&&(b+=", \n"),b+=c+f+" : "+t.__string_rec(a[f],c));c=c.substring(1);return b+("\n"+c+"}");case "string":return a;default:return String(a)}};var L=require("child_process"),
I=require("fs"),M=require("path"),v=require("buffer").Buffer,p=function(){};p.__name__=!0;p.parse=function(a){if(p.PATTERN.match(a)){a=new p;a.path=p.PATTERN.matched(1);a.line=l.parseInt(p.PATTERN.matched(2));switch(p.PATTERN.matched(3)){case "character":a.character=l.parseInt(p.PATTERN.matched(4));a.content=p.PATTERN.matched(7);break;case "characters":a.characters={start:l.parseInt(p.PATTERN.matched(4)),end:l.parseInt(p.PATTERN.matched(6))};a.content=p.PATTERN.matched(7);break;case "lines":a.lines=
{start:l.parseInt(p.PATTERN.matched(4)),end:l.parseInt(p.PATTERN.matched(6))},a.content=p.PATTERN.matched(7)}return a}return null};var C=function(a,c){null==c&&(c=!0);null==a&&(a="haxe");this.haxePath=a;this.verbose=c};C.__name__=!0;C.prototype={start:function(a){this.stop();this.buffer=new D;this.nextMessageLength=-1;this.process=L.spawn(this.haxePath,["-v","--wait","stdio"]);this.process.on("exit",k(this,this.handleExit));this.process.stderr.on("data",k(this,this.handleData));this.process.stdout.on("data",
function(a){});a(null)},stop:function(){if(null!=this.process){this.process.removeAllListeners();try{this.process.kill()}catch(c){}this.process=null}for(var a=this.requestsHead;null!=a;)a.processResult(null),a=a.next;this.requestsHead=this.requestsTail=this.currentRequest=null},query:function(a,c,f,b,d){a=new E(a,c,f,b,d);null==this.requestsHead?this.requestsHead=this.requestsTail=a:(this.requestsTail.next=a,a.prev=this.requestsTail,this.requestsTail=a);this.checkQueue()},checkQueue:function(){null==
this.currentRequest&&null!=this.requestsHead&&(this.currentRequest=this.requestsHead,this.requestsHead=this.currentRequest.next,this.process.stdin.write(this.currentRequest.prepareBody()))},handleData:function(a){for(this.buffer.append(a);;){if(-1==this.nextMessageLength){a=this.buffer.tryReadLength();if(-1==a)break;this.nextMessageLength=a}a=this.buffer.tryReadContent(this.nextMessageLength);if(null==a)break;this.nextMessageLength=-1;if(null!=this.currentRequest){var c=this.currentRequest;this.currentRequest=
null;c.processResult(a);this.checkQueue()}}},handleExit:function(a,c){}};var D=function(a){null==a&&(a=8192);this.size=a;this.buffer=new v(a);this.index=0};D.__name__=!0;D.prototype={append:function(a){if(this.buffer.length-this.index>=a.length)a.copy(this.buffer,this.index,0,a.length);else{var c=(Math.ceil((this.index+a.length)/this.size)+1)*this.size|0;0==this.index?(this.buffer=new v(c),a.copy(this.buffer,0,0,a.length)):this.buffer=v.concat([this.buffer.slice(0,this.index),a],c)}this.index+=a.length},
tryReadLength:function(){if(4>this.index)return-1;var a=this.buffer.readInt32LE(0);this.buffer=this.buffer.slice(4);this.index-=4;return a},tryReadContent:function(a){if(this.index<a)return null;var c=this.buffer.toString("utf-8",0,a);this.buffer.copy(this.buffer,0,a);this.index-=a;return c}};var E=function(a,c,f,b,d){this.args=a;this.stdin=c;this.onResult=f;this.onError=b;this.onMessage=d};E.__name__=!0;E.prototype={prepareBody:function(){null!=this.stdin&&(this.args=this.args.concat(["-D","display-stdin"]));
for(var a=new v(4),c=[a],f=0,b=0,d=this.args;b<d.length;){var e=d[b];++b;e=new v(""+e+"\n");c.push(e);f+=e.length}null!=this.stdin&&(b=new v([1]),c.push(b),d=new v(this.stdin),c.push(d),f+=d.length+b.length);a.writeInt32LE(f,0);return v.concat(c,f+4)},processResult:function(a){if(null==a)this.onResult(null);else{var c="",f=!1,b=0;for(a=a.split("\n");b<a.length;){var e=a[b];++b;switch(e.charCodeAt(0)){case 1:e=d.replace(e.substring(1),"\u0001","\n");if(null!=this.onMessage)this.onMessage(e);break;
case 2:f=!0;break;case 65:if(null!=this.onMessage)this.onMessage(e);break;default:c+=null==e?"null":""+e,c+="\n"}}c=d.trim(c);if(f)this.onError(c);else this.onResult(c)}}};var F=function(){this.excludeLowerPriority=!1;this.inclusionPriority=2;this.disableForSelector=".source.haxe .comment, .source.hx .comment";this.selector=".source.haxe, .source.hx"};F.__name__=!0;F.prototype={dispose:function(){},getSuggestions:function(a){return new Promise(function(a,b){a([])})}};var B=function(a){u.call(this);
this.hxml=a};B.__name__=!0;B.__super__=u;B.prototype=h(u.prototype,{start:function(a){null==a&&(a=!1);var c=this;this.args=["--cwd",this.hxml.getParent().getPath()];a&&this.args.push("-v");this.args.push(this.hxml.getBaseName());e.server.query(this.args,null,function(a){c.emit("end",0)},function(a){a=d.trim(a);c.emit("error",a);c.emit("end",null)},function(a){c.emit("message",a)});this.emit("start",null)}});var e=b.xxx.IDE=function(){};e.__name__=!0;e.activate=function(a){e.disposables=new m;e.emitter=
new u;e.statusbar=new y;e.server=new C(atom.config.get("xxx.haxe_path"));e.projectPaths=atom.project.getPaths();z.delay(function(){e.server.start(function(a){null!=a?atom.notifications.addWarning(a):e.disposables.add(atom.commands.add("atom-workspace","xxx:build",function(a){a=a.target.getAttribute("data-path");null!=a&&"hxml"==n.extension(a)&&null!=e.hxml&&a!=e.hxml.getPath()&&e.selectHxml(a);e.build()}))})},atom.config.get("xxx.haxe_server_startdelay"));e.searchHxmlFiles(null,null,function(c){e.hxmlFiles=
c;null!=a&&null!=a.hxml?-1!=e.hxmlFiles.indexOf(a.hxml)&&e.selectHxml(a.hxml):e.selectHxml(c[0]);e.disposables.add(atom.project.onDidChangePaths(function(a){for(var c=[],b=0;b<a.length;){var f=a[b];++b;for(var d=!0,g=0,h=e.projectPaths;g<h.length;){var k=h[g];++g;if(k==f){d=!1;break}}d&&c.push(f)}e.searchHxmlFiles(c,null,function(a){e.hxmlFiles=e.hxmlFiles.concat(a)});return e.projectPaths=a}));e.disposables.add(atom.workspace.observeTextEditors(function(a){var c=a.getPath();if(null!=c&&"hx"==n.extension(c))a.onDidChange(function(a){})}))})};
e.serialize=function(){return{hxml:null!=e.hxml?e.hxml.getPath():null}};e.deactivate=function(){e.disposables.dispose();e.server.stop()};e.onSelectHxml=function(a){return e.emitter.on("hxml_select",a)};e.onBuild=function(a){return e.emitter.on("build",a)};e.selectHxml=function(a){if(null==a)e.hxml=null;else{if(null!=e.hxml&&a==e.hxml.getPath())return;e.hxml=new x(a)}e.emitter.emit("hxml_select",e.hxml)};e.build=function(){if(null==e.hxml)return atom.notifications.addWarning("No hxml file selected"),
null;var a=new B(e.hxml);new r(a);e.emitter.emit("build",a);a.start();return a};e.searchHxmlFiles=function(a,c,b){null==c&&(c=3);null==a&&(a=atom.project.getPaths());for(var f=function(a,b,d){null==d&&(d=0);var e=[];I.readdir(a,function(g,h){if(null!=g)b(e);else{var A=h.length;if(0==A)b(e);else for(g=0;g<h.length;){var k=[h[g]];++g;var l=M.resolve(a,k[0]);k[0]=l;I.stat(k[0],function(a){return function(g,h){null!=h&&h.isDirectory()?d<c?(g=a[0],h=function(){return function(a){e=e.concat(a);0==--A&&
b(e)}}(),f(g,h,d+1)):0==--A&&b(e):("hxml"==n.extension(a[0])&&"extraParams.hxml"!=n.withoutDirectory(a[0])&&e.push(a[0]),0==--A&&b(e))}}(k))}}})},d=[],e=0,g=0;g<a.length;){var h=a[g];++g;f(h,function(c){d=d.concat(c);(e+=1)==a.length&&b(d)})}};e.getConfig=function(a){return atom.config.get("xxx."+a)};e.consumeStatusBar=function(a){a.addLeftTile({item:e.statusbar.element,priority:-100})};e.provideAutoCompletion=function(){return new F};e.provideService=function(){return{getHxml:function(){return e.hxml},
selectHxml:e.selectHxml,build:e.build}};var G=function(a,c){this.error=c;this.element=window.document.createElement("li");this.element.classList.add("message","error");var b=window.document.createElement("i");b.textContent=l.string(a+1);this.element.appendChild(b);a=window.document.createElement("span");a.classList.add("path");a.textContent=c.path;this.element.appendChild(a);a=window.document.createElement("span");a.classList.add("line");a.textContent=null==c.line?"null":""+c.line;this.element.appendChild(a);
null!=c.characters&&(a=window.document.createElement("span"),a.classList.add("start"),a.textContent=l.string(c.characters.start),this.element.appendChild(a),a=window.document.createElement("span"),a.classList.add("end"),a.textContent=l.string(c.characters.end),this.element.appendChild(a));a=window.document.createElement("span");a.classList.add("content");a.textContent=c.content;this.element.appendChild(a)};G.__name__=!0;G.prototype={select:function(){}};var r=function(a){var c=this;null!=r.current&&
r.current.destroy();r.current=this;this.element=window.document.createElement("div");this.element.classList.add("xxx-build","resizer","native-key-bindings");this.element.setAttribute("tabindex","-1");this.messages=window.document.createElement("ol");this.messages.classList.add("messages","scroller");this.element.appendChild(this.messages);this.panel=atom.workspace.addBottomPanel({item:this.element,visible:!0});var b=[];a.on("start",function(){b=[]});a.on("message",function(a){c.log(a)});a.on("error",
function(a){for(var d=0,f=a.split("\n");d<f.length;){var e=f[d];++d;e=[p.parse(e)];if(null==e[0])c.log(a,"error");else{b.push(e[0]);var g=[new G(c.messages.children.length,e[0])];g[0].element.onclick=function(a,b){return function(c){a[0].select();c.ctrlKey&&r.openErrorPosition(b[0])}}(g,e);c.messages.appendChild(g[0].element)}}});a.on("end",function(d){if(0==d)0==c.messages.children.length&&c.panel.hide();else if(0<b.length){d=b[0];var e=a.hxml.getPath(),f=n.directory(e)+"/"+d.path;(new x(f,!1)).existsSync()||
(e=atom.project.relativizePath(e),d.path=e[0]+"/"+d.path)}});this.element.addEventListener("click",k(this,this.handleClick),!1);window.addEventListener("keydown",function(a){},!1)};r.__name__=!0;r.openPosition=function(a,b,d,e,g,h){null==g&&(g=!0);null==e&&(e=!0);atom.workspace.open(a,{initialLine:b,initialColumn:d,activatePane:e,searchAllPanes:g}).then(function(a){null!=h&&h(a)})};r.openErrorPosition=function(a){var b=a.line-1;r.openPosition(a.path,b,a.character,null,null,function(c){null!=a.characters&&
c.setSelectedBufferRange(new J(new H(b,a.characters.start),new H(b,a.characters.end)))})};r.prototype={destroy:function(){this.panel.destroy()},log:function(a,b){a=d.trim(a);if(0!=a.length){var c=window.document.createElement("li");c.classList.add("message");null!=b&&c.classList.add(b);c.textContent=a;this.messages.appendChild(c)}},handleClick:function(a){a.ctrlKey&&this.panel.hide()}};var y=function(){var a=this;this.element=window.document.createElement("div");this.element.classList.add("status-bar-xxx",
"inline-block");this.icon=window.document.createElement("span");this.icon.classList.add("icon-haxe");this.element.appendChild(this.icon);this.info=window.document.createElement("a");this.info.classList.add("info");this.element.appendChild(this.info);this.meta=window.document.createElement("span");this.meta.classList.add("meta");this.element.appendChild(this.meta);e.emitter.on("hxml_select",k(this,this.changeHxml));e.emitter.on("build",function(b){var c=null,d=0;b.on("start",function(){var b=process.hrtime();
c=(1E9*b[0]+b[1])/1E6;a.changeStatus("active")});b.on("message",function(a){});b.on("error",function(b){d+=1;a.changeStatus("error")});b.on("end",function(b){if(0==b){a.changeStatus("success");b=process.hrtime();b=((1E9*b[0]+b[1])/1E6-c)/1E3;b=null==b?"null":""+b;var e=b.indexOf(".");a.meta.textContent=b.substring(0,e)+b.substring(e,3)+"s"}else a.changeStatus("error"),a.meta.textContent="("+d+")"})});this.info.addEventListener("click",k(this,this.handleClickInfo),!1)};y.__name__=!0;y.getRelativePath=
function(a){a=atom.project.relativizePath(a);var b=a[0].split("/");return b[b.length-1]+"/"+a[1]};y.prototype={dispose:function(){this.info.removeEventListener("click",k(this,this.handleClickInfo));null!=this.contextMenu&&this.contextMenu.dispose()},changeHxml:function(a){null==a?(this.icon.style.display="none",this.info.textContent=""):(this.icon.style.display="inline-block",a=y.getRelativePath(a.getPath()),this.info.textContent=n.withoutExtension(a));this.meta.textContent="";this.buildContextMenu()},
changeStatus:function(a){a!=this.status&&(null!=this.status&&(this.icon.classList.remove(this.status),this.info.classList.remove(this.status)),this.status=a,null!=a&&(this.icon.classList.add(a),this.info.classList.add(a)))},buildContextMenu:function(){null!=this.contextMenu&&this.contextMenu.dispose();var a=[];null!=e.hxml&&(a.push({label:"Build",command:"xxx:build"}),a.push({type:"separator"}));for(var b=0,d=e.hxmlFiles;b<d.length;){var g=d[b];++b;null!=e.hxml&&e.hxml.getPath()==g||a.push({label:y.getRelativePath(g),
command:"xxx:select-hxml"})}this.contextMenu=atom.contextMenu.add({".status-bar-xxx .info":a})},handleClickInfo:function(a){a.ctrlKey?e.build():null!=e.hxml&&atom.workspace.open(e.hxml.getPath())}};var K=0;String.__name__=!0;Array.__name__=!0;Date.__name__=["Date"];module.exports=e;p.PATTERN=new q("^\\s*(.+):([0-9]+):\\s*(characters*|lines)\\s([0-9]+)(-([0-9]+))?\\s:\\s(.+)$","i");e.EVENT_SELECT_HXML="hxml_select";e.EVENT_BUILD="build"})("undefined"!=typeof exports?exports:"undefined"!=typeof window?
window:"undefined"!=typeof self?self:this);
