var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,h,k){c!=Array.prototype&&c!=Object.prototype&&(c[h]=k.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var h=0;return $jscomp.iteratorPrototype(function(){return h<c.length?{done:!1,value:c[h++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.iteratorFromArray=function(c,h){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var k=0,l={next:function(){if(k<c.length){var d=k++;return{value:h(d,c[d]),done:!1}}l.next=function(){return{done:!0,value:void 0}};return l.next()}};l[Symbol.iterator]=function(){return l};return l};
$jscomp.polyfill=function(c,h,k,l){if(h){k=$jscomp.global;c=c.split(".");for(l=0;l<c.length-1;l++){var d=c[l];d in k||(k[d]={});k=k[d]}c=c[c.length-1];l=k[c];h=h(l);h!=l&&null!=h&&$jscomp.defineProperty(k,c,{configurable:!0,writable:!0,value:h})}};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(c){return c})}},"es6","es3");
$jscomp.checkStringArgs=function(c,h,k){if(null==c)throw new TypeError("The 'this' value for String.prototype."+k+" must not be null or undefined");if(h instanceof RegExp)throw new TypeError("First argument to String.prototype."+k+" must not be a regular expression");return c+""};
$jscomp.polyfill("String.prototype.endsWith",function(c){return c?c:function(c,k){var h=$jscomp.checkStringArgs(this,c,"endsWith");c+="";void 0===k&&(k=h.length);k=Math.max(0,Math.min(k|0,h.length));for(var d=c.length;0<d&&0<k;)if(h[--k]!=c[--d])return!1;return 0>=d}},"es6","es3");$jscomp.makeIterator=function(c){$jscomp.initSymbolIterator();var h=c[Symbol.iterator];return h?h.call(c):$jscomp.arrayIterator(c)};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(c){function h(){this.batch_=null}function k(e){return e instanceof d?e:new d(function(c,d){c(e)})}if(c&&!$jscomp.FORCE_POLYFILL_PROMISE)return c;h.prototype.asyncExecute=function(e){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(e);return this};h.prototype.asyncExecuteBatch_=function(){var e=this;this.asyncExecuteFunction(function(){e.executeBatch_()})};var l=$jscomp.global.setTimeout;h.prototype.asyncExecuteFunction=function(e){l(e,
0)};h.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var e=this.batch_;this.batch_=[];for(var c=0;c<e.length;++c){var d=e[c];delete e[c];try{d()}catch(A){this.asyncThrow_(A)}}}this.batch_=null};h.prototype.asyncThrow_=function(e){this.asyncExecuteFunction(function(){throw e;})};var d=function(e){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var c=this.createResolveAndReject_();try{e(c.resolve,c.reject)}catch(w){c.reject(w)}};d.prototype.createResolveAndReject_=
function(){function e(e){return function(k){d||(d=!0,e.call(c,k))}}var c=this,d=!1;return{resolve:e(this.resolveTo_),reject:e(this.reject_)}};d.prototype.resolveTo_=function(e){if(e===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(e instanceof d)this.settleSameAsPromise_(e);else{a:switch(typeof e){case "object":var c=null!=e;break a;case "function":c=!0;break a;default:c=!1}c?this.resolveToNonPromiseObj_(e):this.fulfill_(e)}};d.prototype.resolveToNonPromiseObj_=function(e){var c=
void 0;try{c=e.then}catch(w){this.reject_(w);return}"function"==typeof c?this.settleSameAsThenable_(c,e):this.fulfill_(e)};d.prototype.reject_=function(e){this.settle_(2,e)};d.prototype.fulfill_=function(e){this.settle_(1,e)};d.prototype.settle_=function(e,c){if(0!=this.state_)throw Error("Cannot settle("+e+", "+c|"): Promise already settled in state"+this.state_);this.state_=e;this.result_=c;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var e=
this.onSettledCallbacks_,c=0;c<e.length;++c)e[c].call(),e[c]=null;this.onSettledCallbacks_=null}};var n=new h;d.prototype.settleSameAsPromise_=function(c){var e=this.createResolveAndReject_();c.callWhenSettled_(e.resolve,e.reject)};d.prototype.settleSameAsThenable_=function(c,d){var e=this.createResolveAndReject_();try{c.call(d,e.resolve,e.reject)}catch(A){e.reject(A)}};d.prototype.then=function(c,k){function e(c,e){return"function"==typeof c?function(e){try{h(c(e))}catch(B){l(B)}}:e}var h,l,n=new d(function(c,
e){h=c;l=e});this.callWhenSettled_(e(c,h),e(k,l));return n};d.prototype.catch=function(c){return this.then(void 0,c)};d.prototype.callWhenSettled_=function(c,d){function e(){switch(k.state_){case 1:c(k.result_);break;case 2:d(k.result_);break;default:throw Error("Unexpected state: "+k.state_);}}var k=this;null==this.onSettledCallbacks_?n.asyncExecute(e):this.onSettledCallbacks_.push(function(){n.asyncExecute(e)})};d.resolve=k;d.reject=function(c){return new d(function(e,d){d(c)})};d.race=function(c){return new d(function(e,
d){for(var h=$jscomp.makeIterator(c),l=h.next();!l.done;l=h.next())k(l.value).callWhenSettled_(e,d)})};d.all=function(c){var e=$jscomp.makeIterator(c),h=e.next();return h.done?k([]):new d(function(c,d){function l(e){return function(d){n[e]=d;v--;0==v&&c(n)}}var n=[],v=0;do n.push(void 0),v++,k(h.value).callWhenSettled_(l(n.length-1),d),h=e.next();while(!h.done)})};return d},"es6","es3");
$jscomp.polyfill("String.prototype.startsWith",function(c){return c?c:function(c,k){var h=$jscomp.checkStringArgs(this,c,"startsWith");c+="";var d=h.length,n=c.length;k=Math.max(0,Math.min(k|0,h.length));for(var e=0;e<n&&k<d;)if(h[k++]!=c[e++])return!1;return e>=n}},"es6","es3");
(function(c){function h(a,b){function f(){}f.prototype=a;a=new f;for(var c in b)a[c]=b[c];b.toString!==Object.prototype.toString&&(a.toString=b.toString);return a}function k(a,b){if(null==b)return null;null==b.__id__&&(b.__id__=S++);var f;null==a.hx__closures__?a.hx__closures__={}:f=a.hx__closures__[b.__id__];null==f&&(f=function(){return f.method.apply(f.scope,arguments)},f.scope=a,f.method=b,a.hx__closures__[b.__id__]=f);return f}c.xxx=c.xxx||{};var l=function(a,b){this.r=new RegExp(a,b.split("u").join(""))};
l.__name__=!0;l.prototype={match:function(a){this.r.global&&(this.r.lastIndex=0);this.r.m=this.r.exec(a);this.r.s=a;return null!=this.r.m},matched:function(a){if(null!=this.r.m&&0<=a&&a<this.r.m.length)return this.r.m[a];throw new y("EReg::matched");}};var d=function(){};d.__name__=!0;d.cca=function(a,b){a=a.charCodeAt(b);if(a==a)return a};d.substr=function(a,b,f){if(null==f)f=a.length;else if(0>f)if(0==b)f=a.length+f;else return"";return a.substr(b,f)};Math.__name__=!0;var n=function(){};n.__name__=
!0;n.string=function(a){return z.__string_rec(a,"")};n.parseInt=function(a){var b=parseInt(a,10);0!=b||120!=d.cca(a,1)&&88!=d.cca(a,1)||(b=parseInt(a));return isNaN(b)?null:b};var e=function(){};e.__name__=!0;e.startsWith=function(a,b){return a.length>=b.length?d.substr(a,0,b.length)==b:!1};e.endsWith=function(a,b){var f=b.length,c=a.length;return c>=f?d.substr(a,c-f,f)==b:!1};e.isSpace=function(a,b){a=d.cca(a,b);return 8<a&&14>a?!0:32==a};e.ltrim=function(a){for(var b=a.length,f=0;f<b&&e.isSpace(a,
f);)++f;return 0<f?d.substr(a,f,b-f):a};e.rtrim=function(a){for(var b=a.length,f=0;f<b&&e.isSpace(a,b-f-1);)++f;return 0<f?d.substr(a,0,b-f):a};e.trim=function(a){return e.ltrim(e.rtrim(a))};e.replace=function(a,b,f){return a.split(b).join(f)};var O=require("atom").CompositeDisposable,w=require("atom").Emitter,A=require("atom").File,D=require("atom").Point,E=require("atom").Range,P=function(){};P.__name__=!0;var v=function(a){var b=this;this.id=setInterval(function(){b.run()},a)};v.__name__=!0;v.delay=
function(a,b){var f=new v(b);f.run=function(){f.stop();a()};return f};v.prototype={stop:function(){null!=this.id&&(clearInterval(this.id),this.id=null)},run:function(){}};var G=function(a,b){this.map=a;this.keys=b;this.index=0;this.count=b.length};G.__name__=!0;G.prototype={hasNext:function(){return this.index<this.count},next:function(){var a=this.map,b=this.keys[this.index++];return null!=q[b]?a.getReserved(b):a.h[b]}};var B=function(){this.h={}};B.__name__=!0;B.__interfaces__=[P];B.prototype={setReserved:function(a,
b){null==this.rh&&(this.rh={});this.rh["$"+a]=b},getReserved:function(a){return null==this.rh?null:this.rh["$"+a]},existsReserved:function(a){return null==this.rh?!1:this.rh.hasOwnProperty("$"+a)},arrayKeys:function(){var a=[],b;for(b in this.h)this.h.hasOwnProperty(b)&&a.push(b);if(null!=this.rh)for(b in this.rh)36==b.charCodeAt(0)&&a.push(b.substr(1));return a}};var t=function(a){switch(a){case ".":case "..":this.dir=a;this.file="";return}var b=a.lastIndexOf("/"),f=a.lastIndexOf("\\");b<f?(this.dir=
d.substr(a,0,f),a=d.substr(a,f+1,null),this.backslash=!0):f<b?(this.dir=d.substr(a,0,b),a=d.substr(a,b+1,null)):this.dir=null;b=a.lastIndexOf(".");-1!=b?(this.ext=d.substr(a,b+1,null),this.file=d.substr(a,0,b)):(this.ext=null,this.file=a)};t.__name__=!0;t.withoutExtension=function(a){a=new t(a);a.ext=null;return a.toString()};t.withoutDirectory=function(a){a=new t(a);a.dir=null;return a.toString()};t.directory=function(a){a=new t(a);return null==a.dir?"":a.dir};t.extension=function(a){a=new t(a);
return null==a.ext?"":a.ext};t.prototype={toString:function(){return(null==this.dir?"":this.dir+(this.backslash?"\\":"/"))+this.file+(null==this.ext?"":"."+this.ext)}};var y=function(a){Error.call(this);this.val=a;this.message=String(a);Error.captureStackTrace&&Error.captureStackTrace(this,y)};y.__name__=!0;y.wrap=function(a){return js.Syntax["instanceof"](a,Error)?a:new y(a)};y.__super__=Error;y.prototype=h(Error.prototype,{});var z=function(){};z.__name__=!0;z.__string_rec=function(a,b){if(null==
a)return"null";if(5<=b.length)return"<...>";var f=js.Syntax["typeof"](a);"function"==f&&(a.__name__||a.__ename__)&&(f="object");switch(f){case "function":return"<function>";case "object":if(a instanceof Array){if(a.__enum__){if(2==a.length)return a[0];f=a[0]+"(";b+="\t";for(var c=2,e=a.length;c<e;){var d=c++;f=2!=d?f+(","+z.__string_rec(a[d],b)):f+z.__string_rec(a[d],b)}return f+")"}f=a.length;c="[";b+="\t";for(e=0;e<f;)d=e++,c+=(0<d?",":"")+z.__string_rec(a[d],b);return c+"]"}try{c=a.toString}catch(W){return"???"}if(null!=
c&&c!=Object.toString&&"function"==js.Syntax["typeof"](c)&&(f=a.toString(),"[object Object]"!=f))return f;f=null;c="{\n";b+="\t";e=null!=a.hasOwnProperty;for(f in a)e&&!a.hasOwnProperty(f)||"prototype"==f||"__class__"==f||"__super__"==f||"__interfaces__"==f||"__properties__"==f||(2!=c.length&&(c+=", \n"),c+=b+f+" : "+z.__string_rec(a[f],b));b=b.substring(1);return c+("\n"+b+"}");case "string":return a;default:return String(a)}};var T=require("child_process"),Q=require("fs"),U=require("path"),x=require("buffer").Buffer,
H=function(){};H.__name__=!0;H.parseFunType=function(a){var b={args:[],ret:""},f=a.split(":");if(1==f.length)a=f[0].split("->"),b.ret=d.substr(a[1],1,null);else{f=a.lastIndexOf("->");b.ret=d.substr(a,f+3,null);var c=a=d.substr(a,0,f-1),g=null;g=function(){var a=c.lastIndexOf(":"),f=d.substr(c,0,a-1),m=f.lastIndexOf(" ");-1!=m&&(f=d.substr(f,m+1,null));m=d.substr(c,a+2,null);e.endsWith(m," -> ")&&(m=d.substr(m,0,m.length-4));c=d.substr(c,0,a-(f.length+1));b.args.unshift([f,m]);0<c.length&&g()};g()}return b};
var r=function(){};r.__name__=!0;r.parse=function(a){if(r.EXPR.match(a)){a=new r;a.path=r.EXPR.matched(1);a.line=n.parseInt(r.EXPR.matched(2));switch(r.EXPR.matched(3)){case "character":a.character=n.parseInt(r.EXPR.matched(4));a.content=r.EXPR.matched(7);break;case "characters":a.characters={start:n.parseInt(r.EXPR.matched(4)),end:n.parseInt(r.EXPR.matched(6))};a.content=r.EXPR.matched(7);break;case "lines":a.lines={start:n.parseInt(r.EXPR.matched(4)),end:n.parseInt(r.EXPR.matched(6))},a.content=
r.EXPR.matched(7)}return a}return null};var I=function(a,b){null==b&&(b=!1);null==a&&(a="haxe");this.haxePath=a;this.verbose=b};I.__name__=!0;I.prototype={start:function(a,b){this.stop();this.buffer=new J;this.nextMessageLength=-1;this.proc=T.spawn(this.haxePath,["-v","--wait","stdio"]);this.proc.on("exit",k(this,this.handleExit));this.proc.stderr.on("data",k(this,this.handleData));if(null!=b)this.proc.stdout.on("data",function(a){b(a.toString())});a(null)},stop:function(){if(null!=this.proc){this.proc.removeAllListeners();
try{this.proc.kill()}catch(b){}this.proc=null}for(var a=this.requestsHead;null!=a;)a.processResult(null),a=a.next;this.requestsHead=this.requestsTail=this.currentRequest=null},query:function(a,b,f,c,e){a=new K(a,b,f,c,e);null==this.requestsHead?this.requestsHead=this.requestsTail=a:(this.requestsTail.next=a,a.prev=this.requestsTail,this.requestsTail=a);this.checkQueue()},checkQueue:function(){null==this.currentRequest&&null!=this.requestsHead&&(this.currentRequest=this.requestsHead,this.requestsHead=
this.currentRequest.next,this.proc.stdin.write(this.currentRequest.prepareBody()))},handleData:function(a){for(this.buffer.append(a);;){if(-1==this.nextMessageLength){a=this.buffer.tryReadLength();if(-1==a)break;this.nextMessageLength=a}a=this.buffer.tryReadContent(this.nextMessageLength);if(null==a)break;this.nextMessageLength=-1;if(null!=this.currentRequest){var b=this.currentRequest;this.currentRequest=null;b.processResult(a);this.checkQueue()}}},handleExit:function(a,b){}};var J=function(a){null==
a&&(a=8192);this.size=a;this.buffer=new x(a);this.index=0};J.__name__=!0;J.prototype={append:function(a){if(this.buffer.length-this.index>=a.length)a.copy(this.buffer,this.index,0,a.length);else{var b=(Math.ceil((this.index+a.length)/this.size)+1)*this.size|0;0==this.index?(this.buffer=new x(b),a.copy(this.buffer,0,0,a.length)):this.buffer=x.concat([this.buffer.slice(0,this.index),a],b)}this.index+=a.length},tryReadLength:function(){if(4>this.index)return-1;var a=this.buffer.readInt32LE(0);this.buffer=
this.buffer.slice(4);this.index-=4;return a},tryReadContent:function(a){if(this.index<a)return null;var b=this.buffer.toString("utf-8",0,a);this.buffer.copy(this.buffer,0,a);this.index-=a;return b}};var K=function(a,b,f,c,e){this.args=a;this.stdin=b;this.onResult=f;this.onError=c;this.onMessage=e};K.__name__=!0;K.prototype={prepareBody:function(){null!=this.stdin&&(this.args=this.args.concat(["-D","display-stdin"]));for(var a=new x(4),b=[a],f=0,c=0,e=this.args;c<e.length;){var d=e[c];++c;d=new x(""+
d+"\n");b.push(d);f+=d.length}null!=this.stdin&&(c=new x([1]),b.push(c),e=new x(this.stdin),b.push(e),f+=e.length+c.length);a.writeInt32LE(f,0);return x.concat(b,f+4)},processResult:function(a){if(null==a)this.onResult(null);else{var b="",f=!1,c=0;for(a=a.split("\n");c<a.length;){var d=a[c];++c;switch(d.charCodeAt(0)){case 1:d=e.replace(d.substring(1),"\u0001","\n");if(null!=this.onMessage)this.onMessage(d);break;case 2:f=!0;break;case 65:if(null!=this.onMessage)this.onMessage(d);break;default:b+=
null==d?"null":""+d,b+="\n"}}b=e.trim(b);if(f)this.onError(b);else this.onResult(b)}}};var p=function(){this.suggestionPriority=3;this.disableForSelector=".source.haxe .comment";this.selector=".source.haxe";var a=this;this.enabled=atom.config.get("xxx.autocomplete").enabled;this.disposables=new O;this.disposables.add(atom.config.observe("xxx.autocomplete",function(b){a.enabled=b.enabled}))};p.__name__=!0;p.createSuggestion=function(a,b){null==b&&(b=!0);var f={type:a.k,text:a.n,description:p.formatDoc(a.d)},
c=a.k;if(null==c)f.text=a.t;else switch(c){case "literal":f.type="keyword";break;case "method":c=a.n+"(";var e=a.n+"(",d=H.parseFunType(a.t);f.rightLabel=d.ret;0<d.args.length&&(c+=" ",e+=" ");for(var g=[],h=[],R=0,V=d.args.length;R<V;){var k=R++,L=d.args[k];g.push(L[0]+" : "+L[1]);h.push("${"+(k+1)+":"+L[0]+"}")}c+=g.join(", ");e+=h.join(", ");0<d.args.length&&(c+=" ",e+=" ");f.displayText=c+")";f.snippet=b?e+")$0":a.n;f.text=null;break;case "static":f.type="method";f.snippet=a.n+"()$0";f.displayText=
a.n+"()";break;case "var":f.type="variable",f.rightLabel=a.t}return f};p.formatDoc=function(a){if(null==a)return"";a=e.trim(a);var b=[],c=0;for(a=a.split("\n");c<a.length;){var d=a[c];++c;b.push(e.trim(d))}return b.join("\n")};p.prototype={getSuggestions:function(a){var b=this;return(new Promise(function(c,d){if(b.enabled&&null!=g.hxml){d=a.editor;d.getCursorBufferPosition();var f=a.bufferPosition,m=a.prefix,h="",k=d.getTextInBufferRange(new E(new D(f.row,0),f));p.EXPR_PREFIX_FIELD.match(k)?(m=".",
h=p.EXPR_PREFIX_FIELD.matched(1),f.column-=h.length):p.EXPR_PREFIX_CALL.match(k)&&(m="(",h=p.EXPR_PREFIX_CALL.matched(1),f.column-=h.length);window.console.log("PREFIX = ["+m+"]["+h+"]");null==b.service?b.service=new M(d):b.service.editor=d;switch(m){case "(":b.service.query(f,null,null).then(function(a){var b=a.getAttribute("d");return{d:null==b?null:e.trim(b),t:e.trim(a.childNodes[0].nodeValue)}}).then(function(a){});break;case ".":if(p.EXPR_ALPHANUMERIC_END.match(k)){c([]);break}b.service.query(f,
null,null).then(function(a){for(var b=[],c=0,f=a.children.length;c<f;){var d=c++;d=a.children[d];var g=d.getElementsByTagName("t")[0].childNodes[0],m=d.getElementsByTagName("d")[0].childNodes[0];b.push({n:d.getAttribute("n"),k:d.getAttribute("k"),t:null==g?null:g.nodeValue,d:null==m?null:e.trim(m.nodeValue)})}return b}).then(function(a){for(var b=[],f=p.EXPR_TYPEPATH.match(k),d=0;d<a.length;){var g=a[d];++d;0<h.length&&!e.startsWith(g.n,h)||f&&p.EXPR_TYPEPATH.matched(2).split(".").pop()==g.n||(g=
p.createSuggestion(g,!f),b.push(g))}c(b)});break;default:b.service.query(f,"toplevel",null).then(function(a){for(var b=[],c=0,f=a.children.length;c<f;){var d=c++;d=a.children[d];var g=d.getAttribute("d");b.push({k:d.getAttribute("k"),n:d.getAttribute("n"),t:d.getAttribute("t"),d:null==g?null:e.trim(g),p:d.getAttribute("p"),c:d.childNodes[0].nodeValue})}return b}).then(function(a){for(var b=new B,f=0;f<a.length;){var d=a[f];++f;var g=d.k;if(null==g)g=null;else switch(g){case "enum":case "literal":case "local":case "package":case "static":g=
d.c;break;case "type":g=d.p;break;default:g=null}if(!(0<m.length&&0!=e.trim(m).length&&null!=g)||e.startsWith(g,m)){g={text:g,type:d.k,description:p.formatDoc(d.d)};var h=d.k;if(null==h)window.console.warn("TODO: "+n.string(d));else switch(h){case "enum":g.type="enum";g.rightLabel=d.t;break;case "global":g.type="global";break;case "literal":g.type="keyword";break;case "local":g.type="value";g.rightLabel=d.t;break;case "package":break;case "static":g.displayText=d.c+"()";g.rightLabel=d.t;g.snippet=
d.c+"()$0";g.type="method";break;case "type":break;default:window.console.warn("TODO: "+n.string(d))}h=d.k;if(null!=q[h]?!b.existsReserved(h):!b.h.hasOwnProperty(h)){h=d.k;var k=[];null!=q[h]?b.setReserved(h,k):b.h[h]=k}d=d.k;(null!=q[d]?b.getReserved(d):b.h[d]).push(g)}}a=[];for(f=new G(b,b.arrayKeys());f.hasNext();)f.next().sort(function(a,b){return a.text>b.text?1:a.text<b.text?-1:0});if(null!=q["static"]?b.existsReserved("static"):b.h.hasOwnProperty("static"))a=a.concat(null!=q["static"]?b.getReserved("static"):
b.h["static"]);if(null!=q.local?b.existsReserved("local"):b.h.hasOwnProperty("local"))a=a.concat(null!=q.local?b.getReserved("local"):b.h.local);if(null!=q.global?b.existsReserved("global"):b.h.hasOwnProperty("global"))a=a.concat(null!=q.global?b.getReserved("global"):b.h.global);if(null!=q.literal?b.existsReserved("literal"):b.h.hasOwnProperty("literal"))a=a.concat(null!=q.literal?b.getReserved("literal"):b.h.literal);if(null!=q.type?b.existsReserved("type"):b.h.hasOwnProperty("type"))a=a.concat(null!=
q.type?b.getReserved("type"):b.h.type);if(null!=q["package"]?b.existsReserved("package"):b.h.hasOwnProperty("package"))a=a.concat(null!=q["package"]?b.getReserved("package"):b.h["package"]);if(null!=q["enum"]?b.existsReserved("enum"):b.h.hasOwnProperty("enum"))a=a.concat(null!=q["enum"]?b.getReserved("enum"):b.h["enum"]);c(a)})}}else c([])}))["catch"](function(a){window.console.error(a);return Promise.resolve([])})},onDidInsertSuggestion:function(a){},dispose:function(){this.disposables.dispose()}};
var F=function(a){w.call(this);this.hxml=a};F.__name__=!0;F.__super__=w;F.prototype=h(w.prototype,{start:function(a){null==a&&(a=!1);var b=this;this.args=["--cwd",this.hxml.getParent().getPath()];a&&this.args.push("-v");this.args.push(this.hxml.getBaseName());this.args.push("--times");window.console.log("%chaxe "+this.args.join(" "),"color:#F1471D;");g.server.query(this.args,null,function(a){0<a.length&&window.console.log("%c"+a,"color:#F1471D;");b.emit("end",0)},function(a){a=e.trim(a);0<a.length&&
window.console.log("%c"+a,"color:#F1471D;");b.emit("error",a);b.emit("end",null)},function(a){window.console.log("%c"+a,"color:#F1471D;");b.emit("message",a)});this.emit("start",null)}});var M=function(a){this.editor=a};M.__name__=!0;M.prototype={query:function(a,b,c){var f=this;return new Promise(function(d,e){null==a&&(a=f.editor.getCursorBufferPosition());var h=f.editor.getTextInBufferRange(new E(new D(0,0),a)),m=h.length;m=""+f.editor.getPath()+"@"+m;null!=b&&(m+="@"+b);m=[g.hxml.getPath(),"--display",
m];null!=c&&(m=m.concat(c));g.server.query(m,h,function(a){a=(new DOMParser).parseFromString(a,"application/xml").documentElement;d(a)},function(a){window.console.warn(a)},function(a){window.console.warn(a);e(a)})})}};var g=c.xxx.IDE=function(){};g.__name__=!0;g.activate=function(a){g.disposables=new O;g.emitter=new w;g.statusbar=new C;g.projectPaths=atom.project.getPaths();g.server=new I(atom.config.get("xxx.haxe_path"),!1);g.searchHxmlFiles(null,null,function(b){g.hxmlFiles=b;null!=a&&null!=a.hxml?
-1!=g.hxmlFiles.indexOf(a.hxml)&&g.selectHxml(a.hxml):g.selectHxml(b[0]);v.delay(function(){g.server.start(function(a){null!=a?atom.notifications.addWarning(a):(g.disposables.add(atom.commands.add("atom-workspace","xxx:build",function(a){a=a.target.getAttribute("data-path");null!=a&&"hxml"==t.extension(a)&&null!=g.hxml&&a!=g.hxml.getPath()&&g.selectHxml(a);g.build()})),g.disposables.add(atom.commands.add("atom-workspace","xxx:goto",function(a){g.goto()})))},function(a){})},1E3*atom.config.get("xxx.haxe_server_startdelay")|
0);g.disposables.add(atom.project.onDidChangePaths(function(a){for(var b=[],c=0;c<a.length;){var f=a[c];++c;for(var d=!0,e=0,h=g.projectPaths;e<h.length;){var k=h[e];++e;if(k==f){d=!1;break}}d&&b.push(f)}g.searchHxmlFiles(b,null,function(a){g.hxmlFiles=g.hxmlFiles.concat(a)});return g.projectPaths=a}));g.disposables.add(atom.workspace.observeTextEditors(function(a){a=a.getPath();null!=a&&t.extension(a)}))})};g.serialize=function(){return{hxml:null!=g.hxml?g.hxml.getPath():null}};g.deactivate=function(){g.disposables.dispose();
g.server.stop()};g.goto=function(){var a=atom.workspace.getActiveTextEditor();if(null!=a){var b=a.getCursorBufferPosition();a.getTextInBufferRange(new E(new D(b.row,0),b))}};g.onSelectHxml=function(a){return g.emitter.on("hxml_select",a)};g.onBuild=function(a){return g.emitter.on("build",a)};g.getConfig=function(a){return atom.config.get("xxx."+a)};g.selectHxml=function(a){if(null==a)g.hxml=null;else{if(null!=g.hxml&&a==g.hxml.getPath())return;g.hxml=new A(a)}g.emitter.emit("hxml_select",g.hxml)};
g.build=function(){if(null==g.hxml)return atom.notifications.addWarning("No hxml file selected"),null;var a=new F(g.hxml);new u(a);g.emitter.emit("build",a);a.start();return a};g.searchHxmlFiles=function(a,b,c){null==a&&(a=atom.project.getPaths());null==b&&(b=atom.config.get("xxx.hxml_search_depth"));for(var f=function(a,c,d){null==d&&(d=0);var e=[];Q.readdir(a,function(g,h){if(null!=g)c(e);else{var k=h.length;if(0==k)c(e);else for(g=0;g<h.length;){var m=[h[g]];++g;var l=U.resolve(a,m[0]);m[0]=l;
Q.stat(m[0],function(a){return function(g,h){null!=h&&h.isDirectory()?d<b?(g=a[0],h=function(){return function(a){e=e.concat(a);0==--k&&c(e)}}(),f(g,h,d+1)):0==--k&&c(e):("hxml"==t.extension(a[0])&&"extraParams.hxml"!=t.withoutDirectory(a[0])&&e.push(a[0]),0==--k&&c(e))}}(m))}}})},d=[],e=0,g=0;g<a.length;){var h=a[g];++g;f(h,function(b){d=d.concat(b);(e+=1)==a.length&&c(d)})}};g.consumeStatusBar=function(a){a.addLeftTile({item:g.statusbar.element,priority:-100})};g.provideAutoCompletion=function(){return new p};
g.provideService=function(){return{getHxml:function(){return g.hxml},selectHxml:g.selectHxml,build:g.build}};var N=function(a,b){this.error=b;this.element=window.document.createElement("li");this.element.classList.add("message","error");var c=window.document.createElement("i");c.textContent=n.string(a+1);this.element.appendChild(c);a=window.document.createElement("span");a.classList.add("path");a.textContent=b.path;this.element.appendChild(a);a=window.document.createElement("span");a.classList.add("line");
a.textContent=null==b.line?"null":""+b.line;this.element.appendChild(a);null!=b.characters&&(a=window.document.createElement("span"),a.classList.add("start"),a.textContent=n.string(b.characters.start),this.element.appendChild(a),a=window.document.createElement("span"),a.classList.add("end"),a.textContent=n.string(b.characters.end),this.element.appendChild(a));a=window.document.createElement("span");a.classList.add("content");a.textContent=b.content;this.element.appendChild(a)};N.__name__=!0;N.prototype=
{select:function(){}};var u=function(a){var b=this;null!=u.current&&u.current.destroy();u.current=this;this.element=window.document.createElement("div");this.element.classList.add("xxx-build","resizer","native-key-bindings");this.element.setAttribute("tabindex","-1");this.messages=window.document.createElement("ol");this.messages.classList.add("messages","scroller");this.element.appendChild(this.messages);this.panel=atom.workspace.addBottomPanel({item:this.element,visible:!0});var c=[];a.on("start",
function(){var a=process.hrtime();b.timeStart=(1E9*a[0]+a[1])/1E6;c=[]});a.on("message",function(a){b.log(a)});a.on("error",function(a){for(var d=0,f=a.split("\n");d<f.length;){var e=f[d];++d;e=[r.parse(e)];if(null==e[0])b.log(a,"error");else{c.push(e[0]);var g=[new N(b.messages.children.length,e[0])];g[0].element.onclick=function(a,b){return function(c){a[0].select();c.ctrlKey&&u.openErrorPosition(b[0])}}(g,e);b.messages.appendChild(g[0].element)}}});a.on("end",function(d){if(0==d)0==b.messages.children.length&&
b.panel.hide();else if(0<c.length){d=c[0];var f=a.hxml.getPath(),e=t.directory(f)+"/"+d.path;(new A(e,!1)).existsSync()||(f=atom.project.relativizePath(f),d.path=f[0]+"/"+d.path)}});this.element.addEventListener("click",k(this,this.handleClick),!1)};u.__name__=!0;u.openPosition=function(a,b,c,d,e,g){null==e&&(e=!0);null==d&&(d=!0);atom.workspace.open(a,{initialLine:b,initialColumn:c,activatePane:d,searchAllPanes:e}).then(function(a){null!=g&&g(a)})};u.openErrorPosition=function(a){var b=a.line-1;
u.openPosition(a.path,b,a.character,null,null,function(c){null!=a.characters&&c.setSelectedBufferRange(new E(new D(b,a.characters.start),new D(b,a.characters.end)))})};u.prototype={destroy:function(){this.panel.destroy()},log:function(a,b){a=e.trim(a);if(0!=a.length){var c=window.document.createElement("li");c.classList.add("message");null!=b&&c.classList.add(b);b=window.document.createElement("span");b.classList.add("time");var d=process.hrtime();b.textContent=n.string((1E9*d[0]+d[1])/1E6-this.timeStart|
0);c.appendChild(b);b=window.document.createElement("span");b.classList.add("content");b.textContent=a;c.appendChild(b);this.messages.appendChild(c)}},handleClick:function(a){a.ctrlKey&&this.panel.hide()}};var C=function(){var a=this;this.element=window.document.createElement("div");this.element.classList.add("status-bar-xxx","inline-block");this.icon=window.document.createElement("span");this.icon.classList.add("icon-haxe");this.element.appendChild(this.icon);this.info=window.document.createElement("a");
this.info.classList.add("info");this.element.appendChild(this.info);this.meta=window.document.createElement("span");this.meta.classList.add("meta");this.element.appendChild(this.meta);g.emitter.on("hxml_select",k(this,this.changeHxml));g.emitter.on("build",function(b){var c=null,d=0;b.on("start",function(){var b=process.hrtime();c=(1E9*b[0]+b[1])/1E6;a.changeStatus("active")});b.on("message",function(a){});b.on("error",function(b){d+=1;a.changeStatus("error")});b.on("end",function(b){if(0==b){a.changeStatus("success");
b=process.hrtime();b=((1E9*b[0]+b[1])/1E6-c)/1E3;b=null==b?"null":""+b;var e=b.indexOf(".");a.meta.textContent=b.substring(0,e)+b.substring(e,3)+"s"}else a.changeStatus("error"),a.meta.textContent="("+d+")"})});this.info.addEventListener("click",k(this,this.handleClickInfo),!1)};C.__name__=!0;C.getRelativePath=function(a){a=atom.project.relativizePath(a);var b=a[0].split("/");return b[b.length-1]+"/"+a[1]};C.prototype={setMeta:function(a){this.meta.textContent=a},dispose:function(){this.info.removeEventListener("click",
k(this,this.handleClickInfo));null!=this.contextMenu&&this.contextMenu.dispose()},changeHxml:function(a){null==a?(this.icon.style.display="none",this.info.textContent=""):(this.icon.style.display="inline-block",a=C.getRelativePath(a.getPath()),this.info.textContent=t.withoutExtension(a));this.meta.textContent="";this.buildContextMenu()},changeStatus:function(a){a!=this.status&&(null!=this.status&&(this.icon.classList.remove(this.status),this.info.classList.remove(this.status)),this.status=a,null!=
a&&(this.icon.classList.add(a),this.info.classList.add(a)))},buildContextMenu:function(){null!=this.contextMenu&&this.contextMenu.dispose();var a=[];null!=g.hxml&&(a.push({label:"Build",command:"xxx:build"}),a.push({type:"separator"}));for(var b=0,c=g.hxmlFiles;b<c.length;){var d=c[b];++b;null!=g.hxml&&g.hxml.getPath()==d||a.push({label:C.getRelativePath(d),command:"xxx:select-hxml"})}this.contextMenu=atom.contextMenu.add({".status-bar-xxx .info":a})},handleClickInfo:function(a){a.ctrlKey?g.build():
null!=g.hxml&&atom.workspace.open(g.hxml.getPath())}};var S=0;String.__name__=!0;Array.__name__=!0;var q={};module.exports=g;r.EXPR=new l("^\\s*(.+):([0-9]+):\\s*(characters*|lines)\\s([0-9]+)(-([0-9]+))?\\s:\\s(.+)$","i");p.EXPR_ALPHANUMERIC_END=new l("[^a-zA-Z0-9_\\]\\)]([\\.0-9]+)$","");p.EXPR_PREFIX_FIELD=new l("\\.([a-zA-Z_][a-zA-Z_0-9]*)$","");p.EXPR_PREFIX_CALL=new l("\\(( *)$","");p.EXPR_TYPEPATH=new l("(import|using)\\s+([a-zA-Z0-9_]+(?:\\.[a-zA-Z0-9_]+)*)(?:\\s+(?:in|as)\\s+([a-zA-Z0-9_]+))?",
"g");g.COLOR_HAXE_1="#F68712";g.COLOR_HAXE_2="#F47216";g.COLOR_HAXE_3="#F1471D";g.COLOR_HAXE_4="#FFF200";g.EVENT_SELECT_HXML="hxml_select";g.EVENT_BUILD="build"})("undefined"!=typeof exports?exports:"undefined"!=typeof window?window:"undefined"!=typeof self?self:this);
