var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(g,r,v){g!=Array.prototype&&g!=Object.prototype&&(g[r]=v.value)};$jscomp.getGlobal=function(g){return"undefined"!=typeof window&&window===g?g:"undefined"!=typeof global&&null!=global?global:g};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(g){return $jscomp.SYMBOL_PREFIX+(g||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var g=$jscomp.global.Symbol.iterator;g||(g=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[g]&&$jscomp.defineProperty(Array.prototype,g,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(g){var r=0;return $jscomp.iteratorPrototype(function(){return r<g.length?{done:!1,value:g[r++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(g){$jscomp.initSymbolIterator();g={next:g};g[$jscomp.global.Symbol.iterator]=function(){return this};return g};$jscomp.makeIterator=function(g){$jscomp.initSymbolIterator();var r=g[Symbol.iterator];return r?r.call(g):$jscomp.arrayIterator(g)};
$jscomp.polyfill=function(g,r,v,A){if(r){v=$jscomp.global;g=g.split(".");for(A=0;A<g.length-1;A++){var m=g[A];m in v||(v[m]={});v=v[m]}g=g[g.length-1];A=v[g];r=r(A);r!=A&&null!=r&&$jscomp.defineProperty(v,g,{configurable:!0,writable:!0,value:r})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(g){function r(){this.batch_=null}function v(d){return d instanceof m?d:new m(function(f,p){f(d)})}if(g&&!$jscomp.FORCE_POLYFILL_PROMISE)return g;r.prototype.asyncExecute=function(d){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(d);return this};r.prototype.asyncExecuteBatch_=function(){var d=this;this.asyncExecuteFunction(function(){d.executeBatch_()})};var A=$jscomp.global.setTimeout;r.prototype.asyncExecuteFunction=function(d){A(d,
0)};r.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=this.batch_;this.batch_=[];for(var f=0;f<d.length;++f){var p=d[f];delete d[f];try{p()}catch(J){this.asyncThrow_(J)}}}this.batch_=null};r.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};var m=function(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var f=this.createResolveAndReject_();try{d(f.resolve,f.reject)}catch(p){f.reject(p)}};m.prototype.createResolveAndReject_=
function(){function d(d){return function(e){p||(p=!0,d.call(f,e))}}var f=this,p=!1;return{resolve:d(this.resolveTo_),reject:d(this.reject_)}};m.prototype.resolveTo_=function(d){if(d===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof m)this.settleSameAsPromise_(d);else{a:switch(typeof d){case "object":var f=null!=d;break a;case "function":f=!0;break a;default:f=!1}f?this.resolveToNonPromiseObj_(d):this.fulfill_(d)}};m.prototype.resolveToNonPromiseObj_=function(d){var f=
void 0;try{f=d.then}catch(p){this.reject_(p);return}"function"==typeof f?this.settleSameAsThenable_(f,d):this.fulfill_(d)};m.prototype.reject_=function(d){this.settle_(2,d)};m.prototype.fulfill_=function(d){this.settle_(1,d)};m.prototype.settle_=function(d,f){if(0!=this.state_)throw Error("Cannot settle("+d+", "+f|"): Promise already settled in state"+this.state_);this.state_=d;this.result_=f;this.executeOnSettledCallbacks_()};m.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var d=
this.onSettledCallbacks_,f=0;f<d.length;++f)d[f].call(),d[f]=null;this.onSettledCallbacks_=null}};var f=new r;m.prototype.settleSameAsPromise_=function(f){var d=this.createResolveAndReject_();f.callWhenSettled_(d.resolve,d.reject)};m.prototype.settleSameAsThenable_=function(f,g){var d=this.createResolveAndReject_();try{f.call(g,d.resolve,d.reject)}catch(J){d.reject(J)}};m.prototype.then=function(f,g){function d(f,d){return"function"==typeof f?function(d){try{r(f(d))}catch(N){e(N)}}:d}var r,e,v=new m(function(f,
d){r=f;e=d});this.callWhenSettled_(d(f,r),d(g,e));return v};m.prototype.catch=function(f){return this.then(void 0,f)};m.prototype.callWhenSettled_=function(d,g){function p(){switch(m.state_){case 1:d(m.result_);break;case 2:g(m.result_);break;default:throw Error("Unexpected state: "+m.state_);}}var m=this;null==this.onSettledCallbacks_?f.asyncExecute(p):this.onSettledCallbacks_.push(function(){f.asyncExecute(p)})};m.resolve=v;m.reject=function(f){return new m(function(d,g){g(f)})};m.race=function(f){return new m(function(d,
g){for(var m=$jscomp.makeIterator(f),e=m.next();!e.done;e=m.next())v(e.value).callWhenSettled_(d,g)})};m.all=function(f){var d=$jscomp.makeIterator(f),g=d.next();return g.done?v([]):new m(function(f,e){function m(e){return function(d){p[e]=d;r--;0==r&&f(p)}}var p=[],r=0;do p.push(void 0),r++,v(g.value).callWhenSettled_(m(p.length-1),e),g=d.next();while(!g.done)})};return m},"es6","es3");
$jscomp.checkStringArgs=function(g,r,v){if(null==g)throw new TypeError("The 'this' value for String.prototype."+v+" must not be null or undefined");if(r instanceof RegExp)throw new TypeError("First argument to String.prototype."+v+" must not be a regular expression");return g+""};
$jscomp.polyfill("String.prototype.startsWith",function(g){return g?g:function(g,v){var r=$jscomp.checkStringArgs(this,g,"startsWith");g+="";var m=r.length,f=g.length;v=Math.max(0,Math.min(v|0,r.length));for(var d=0;d<f&&v<m;)if(r[v++]!=g[d++])return!1;return d>=f}},"es6","es3");
(function(g,r){function v(a,b){function c(){}c.prototype=a;a=new c;for(var e in b)a[e]=b[e];b.toString!==Object.prototype.toString&&(a.toString=b.toString);return a}function A(a,b){if(null==b)return null;null==b.__id__&&(b.__id__=ba++);var c;null==a.hx__closures__?a.hx__closures__={}:c=a.hx__closures__[b.__id__];null==c&&(c=function(){return c.method.apply(c.scope,arguments)},c.scope=a,c.method=b,a.hx__closures__[b.__id__]=c);return c}g.xxx=g.xxx||{};var m=function(a,b){this.r=new RegExp(a,b.split("u").join(""))};
m.__name__=["EReg"];m.prototype={match:function(a){this.r.global&&(this.r.lastIndex=0);this.r.m=this.r.exec(a);this.r.s=a;return null!=this.r.m},matched:function(a){if(null!=this.r.m&&0<=a&&a<this.r.m.length)return this.r.m[a];throw new n("EReg::matched");},__class__:m};var f=function(){};f.__name__=["HxOverrides"];f.cca=function(a,b){a=a.charCodeAt(b);if(a==a)return a};f.substr=function(a,b,c){if(null==c)c=a.length;else if(0>c)if(0==b)c=a.length+c;else return"";return a.substr(b,c)};f.remove=function(a,
b){b=a.indexOf(b);if(-1==b)return!1;a.splice(b,1);return!0};f.iter=function(a){return{cur:0,arr:a,hasNext:function(){return this.cur<this.arr.length},next:function(){return this.arr[this.cur++]}}};Math.__name__=["Math"];var d=function(){};d.__name__=["Std"];d.string=function(a){return B.__string_rec(a,"")};d.parseInt=function(a){var b=parseInt(a,10);0!=b||120!=f.cca(a,1)&&88!=f.cca(a,1)||(b=parseInt(a));return isNaN(b)?null:b};var G=function(){this.b=""};G.__name__=["StringBuf"];G.prototype={__class__:G};
var p=function(){};p.__name__=["StringTools"];p.htmlUnescape=function(a){return a.split("&gt;").join(">").split("&lt;").join("<").split("&quot;").join('"').split("&#039;").join("'").split("&amp;").join("&")};p.startsWith=function(a,b){return a.length>=b.length?f.substr(a,0,b.length)==b:!1};p.isSpace=function(a,b){a=f.cca(a,b);return 8<a&&14>a?!0:32==a};p.ltrim=function(a){for(var b=a.length,c=0;c<b&&p.isSpace(a,c);)++c;return 0<c?f.substr(a,c,b-c):a};p.rtrim=function(a){for(var b=a.length,c=0;c<b&&
p.isSpace(a,b-c-1);)++c;return 0<c?f.substr(a,0,b-c):a};p.trim=function(a){return p.ltrim(p.rtrim(a))};p.replace=function(a,b,c){return a.split(b).join(c)};var J=function(){};J.__name__=["Type"];J.getClassName=function(a){a=a.__name__;return null==a?null:a.join(".")};var e=function(a){this.nodeType=a;this.children=[];this.attributeMap=new L};e.__name__=["Xml"];e.parse=function(a){return F.parse(a)};e.createElement=function(a){var b=new e(e.Element);if(b.nodeType!=e.Element)throw new n("Bad node type, expected Element but found "+
b.nodeType);b.nodeName=a;return b};e.createPCData=function(a){var b=new e(e.PCData);if(b.nodeType==e.Document||b.nodeType==e.Element)throw new n("Bad node type, unexpected "+b.nodeType);b.nodeValue=a;return b};e.createCData=function(a){var b=new e(e.CData);if(b.nodeType==e.Document||b.nodeType==e.Element)throw new n("Bad node type, unexpected "+b.nodeType);b.nodeValue=a;return b};e.createComment=function(a){var b=new e(e.Comment);if(b.nodeType==e.Document||b.nodeType==e.Element)throw new n("Bad node type, unexpected "+
b.nodeType);b.nodeValue=a;return b};e.createDocType=function(a){var b=new e(e.DocType);if(b.nodeType==e.Document||b.nodeType==e.Element)throw new n("Bad node type, unexpected "+b.nodeType);b.nodeValue=a;return b};e.createProcessingInstruction=function(a){var b=new e(e.ProcessingInstruction);if(b.nodeType==e.Document||b.nodeType==e.Element)throw new n("Bad node type, unexpected "+b.nodeType);b.nodeValue=a;return b};e.createDocument=function(){return new e(e.Document)};e.prototype={get:function(a){if(this.nodeType!=
e.Element)throw new n("Bad node type, expected Element but found "+this.nodeType);var b=this.attributeMap;return null!=E[a]?b.getReserved(a):b.h[a]},set:function(a,b){if(this.nodeType!=e.Element)throw new n("Bad node type, expected Element but found "+this.nodeType);var c=this.attributeMap;null!=E[a]?c.setReserved(a,b):c.h[a]=b},exists:function(a){if(this.nodeType!=e.Element)throw new n("Bad node type, expected Element but found "+this.nodeType);var b=this.attributeMap;return null!=E[a]?b.existsReserved(a):
b.h.hasOwnProperty(a)},elements:function(){if(this.nodeType!=e.Document&&this.nodeType!=e.Element)throw new n("Bad node type, expected Element or Document but found "+this.nodeType);for(var a=[],b=0,c=this.children;b<c.length;){var u=c[b];++b;u.nodeType==e.Element&&a.push(u)}return f.iter(a)},elementsNamed:function(a){if(this.nodeType!=e.Document&&this.nodeType!=e.Element)throw new n("Bad node type, expected Element or Document but found "+this.nodeType);for(var b=[],c=0,u=this.children;c<u.length;){var d=
u[c];++c;if(d.nodeType==e.Element){if(d.nodeType!=e.Element)throw new n("Bad node type, expected Element but found "+d.nodeType);var q=d.nodeName==a}else q=!1;q&&b.push(d)}return f.iter(b)},firstElement:function(){if(this.nodeType!=e.Document&&this.nodeType!=e.Element)throw new n("Bad node type, expected Element or Document but found "+this.nodeType);for(var a=0,b=this.children;a<b.length;){var c=b[a];++a;if(c.nodeType==e.Element)return c}return null},addChild:function(a){if(this.nodeType!=e.Document&&
this.nodeType!=e.Element)throw new n("Bad node type, expected Element or Document but found "+this.nodeType);null!=a.parent&&a.parent.removeChild(a);this.children.push(a);a.parent=this},removeChild:function(a){if(this.nodeType!=e.Document&&this.nodeType!=e.Element)throw new n("Bad node type, expected Element or Document but found "+this.nodeType);return f.remove(this.children,a)?(a.parent=null,!0):!1},__class__:e};var aa=require("atom").CompositeDisposable,P=require("atom").Emitter,X=require("atom").File,
Q=require("atom").Point,N=require("atom").Range,Y=function(){};Y.__name__=["haxe","IMap"];var M=function(a){var b=this;this.id=setInterval(function(){b.run()},a)};M.__name__=["haxe","Timer"];M.delay=function(a,b){var c=new M(b);c.run=function(){c.stop();a()};return c};M.prototype={stop:function(){null!=this.id&&(clearInterval(this.id),this.id=null)},run:function(){},__class__:M};var L=function(){this.h={}};L.__name__=["haxe","ds","StringMap"];L.__interfaces__=[Y];L.prototype={setReserved:function(a,
b){null==this.rh&&(this.rh={});this.rh["$"+a]=b},getReserved:function(a){return null==this.rh?null:this.rh["$"+a]},existsReserved:function(a){return null==this.rh?!1:this.rh.hasOwnProperty("$"+a)},__class__:L};var z=function(a){switch(a){case ".":case "..":this.dir=a;this.file="";return}var b=a.lastIndexOf("/"),c=a.lastIndexOf("\\");b<c?(this.dir=f.substr(a,0,c),a=f.substr(a,c+1,null),this.backslash=!0):c<b?(this.dir=f.substr(a,0,b),a=f.substr(a,b+1,null)):this.dir=null;b=a.lastIndexOf(".");-1!=b?
(this.ext=f.substr(a,b+1,null),this.file=f.substr(a,0,b)):(this.ext=null,this.file=a)};z.__name__=["haxe","io","Path"];z.withoutExtension=function(a){a=new z(a);a.ext=null;return a.toString()};z.withoutDirectory=function(a){a=new z(a);a.dir=null;return a.toString()};z.directory=function(a){a=new z(a);return null==a.dir?"":a.dir};z.extension=function(a){a=new z(a);return null==a.ext?"":a.ext};z.prototype={toString:function(){return(null==this.dir?"":this.dir+(this.backslash?"\\":"/"))+this.file+(null==
this.ext?"":"."+this.ext)},__class__:z};var x=function(a,b,c){this.xml=b;this.message=a;this.position=c;this.lineNumber=1;for(a=this.positionAtLine=0;a<c;){var e=a++;e=b.charCodeAt(e);10==e?(this.lineNumber++,this.positionAtLine=0):13!=e&&this.positionAtLine++}};x.__name__=["haxe","xml","XmlParserException"];x.prototype={toString:function(){return J.getClassName(B.getClass(this))+": "+this.message+" at line "+this.lineNumber+" char "+this.positionAtLine},__class__:x};var F=function(){};F.__name__=
["haxe","xml","Parser"];F.parse=function(a,b){null==b&&(b=!1);var c=e.createDocument();F.doParse(a,b,0,c);return c};F.doParse=function(a,b,c,u){null==c&&(c=0);for(var w=null,q=1,h=1,g=null,k=0,H=0,m=0,l=a.charCodeAt(c),t=new G,p=1,W=-1;l==l;){switch(q){case 0:switch(l){case 9:case 10:case 13:case 32:break;default:q=h;continue}break;case 1:if(60==l)q=0,h=2;else{k=c;q=13;continue}break;case 2:switch(l){case 33:if(91==a.charCodeAt(c+1)){c+=2;if("CDATA["!=f.substr(a,c,6).toUpperCase())throw new n(new x("Expected <![CDATA[",
a,c));c+=5;q=17}else if(68==a.charCodeAt(c+1)||100==a.charCodeAt(c+1)){if("OCTYPE"!=f.substr(a,c+2,6).toUpperCase())throw new n(new x("Expected <!DOCTYPE",a,c));c+=8;q=16}else{if(45!=a.charCodeAt(c+1)||45!=a.charCodeAt(c+2))throw new n(new x("Expected \x3c!--",a,c));c+=2;q=15}k=c+1;break;case 47:if(null==u)throw new n(new x("Expected node name",a,c));k=c+1;q=0;h=10;break;case 63:q=14;k=c;break;default:q=3;k=c;continue}break;case 3:if(!(97<=l&&122>=l||65<=l&&90>=l||48<=l&&57>=l||58==l||46==l||95==
l||45==l)){if(c==k)throw new n(new x("Expected node name",a,c));w=e.createElement(f.substr(a,k,c-k));u.addChild(w);++H;q=0;h=4;continue}break;case 4:switch(l){case 47:q=11;break;case 62:q=9;break;default:q=5;k=c;continue}break;case 5:if(!(97<=l&&122>=l||65<=l&&90>=l||48<=l&&57>=l||58==l||46==l||95==l||45==l)){if(k==c)throw new n(new x("Expected attribute name",a,c));g=f.substr(a,k,c-k);if(w.exists(g))throw new n(new x("Duplicate attribute ["+g+"]",a,c));q=0;h=6;continue}break;case 6:if(61==l)q=0,
h=7;else throw new n(new x("Expected =",a,c));break;case 7:switch(l){case 34:case 39:t=new G;q=8;k=c+1;W=l;break;default:throw new n(new x('Expected "',a,c));}break;case 8:switch(l){case 38:p=c-k;t.b+=null==p?f.substr(a,k,null):f.substr(a,k,p);q=18;p=8;k=c+1;break;case 60:case 62:if(b)throw new n(new x("Invalid unescaped "+String.fromCharCode(l)+" in attribute value",a,c));l==W&&(h=c-k,t.b+=null==h?f.substr(a,k,null):f.substr(a,k,h),h=t.b,t=new G,w.set(g,h),q=0,h=4);break;default:l==W&&(h=c-k,t.b+=
null==h?f.substr(a,k,null):f.substr(a,k,h),h=t.b,t=new G,w.set(g,h),q=0,h=4)}break;case 9:k=c=F.doParse(a,b,c,w);q=1;break;case 10:if(!(97<=l&&122>=l||65<=l&&90>=l||48<=l&&57>=l||58==l||46==l||95==l||45==l)){if(k==c)throw new n(new x("Expected node name",a,c));h=f.substr(a,k,c-k);if(u.nodeType!=e.Element)throw new n("Bad node type, expected Element but found "+u.nodeType);if(h!=u.nodeName){if(u.nodeType!=e.Element)throw new n("Bad node type, expected Element but found "+u.nodeType);throw new n(new x("Expected </"+
u.nodeName+">",a,c));}q=0;h=12;continue}break;case 11:if(62==l)q=1;else throw new n(new x("Expected >",a,c));break;case 12:if(62==l)return 0==H&&u.addChild(e.createPCData("")),c;throw new n(new x("Expected >",a,c));case 13:60==l?(h=c-k,t.b+=null==h?f.substr(a,k,null):f.substr(a,k,h),h=e.createPCData(t.b),t=new G,u.addChild(h),++H,q=0,h=2):38==l&&(p=c-k,t.b+=null==p?f.substr(a,k,null):f.substr(a,k,p),q=18,p=13,k=c+1);break;case 14:63==l&&62==a.charCodeAt(c+1)&&(++c,l=f.substr(a,k+1,c-k-2),u.addChild(e.createProcessingInstruction(l)),
++H,q=1);break;case 15:45==l&&45==a.charCodeAt(c+1)&&62==a.charCodeAt(c+2)&&(u.addChild(e.createComment(f.substr(a,k,c-k))),++H,c+=2,q=1);break;case 16:91==l?++m:93==l?--m:62==l&&0==m&&(u.addChild(e.createDocType(f.substr(a,k,c-k))),++H,q=1);break;case 17:93==l&&93==a.charCodeAt(c+1)&&62==a.charCodeAt(c+2)&&(l=e.createCData(f.substr(a,k,c-k)),u.addChild(l),++H,c+=2,q=1);break;case 18:if(59==l){k=f.substr(a,k,c-k);if(35==k.charCodeAt(0))k=120==k.charCodeAt(1)?d.parseInt("0"+f.substr(k,1,k.length-1)):
d.parseInt(f.substr(k,1,k.length-1)),t.b+=String.fromCharCode(k);else if(l=F.escapes,null!=E[k]?l.existsReserved(k):l.h.hasOwnProperty(k))l=F.escapes,k=null!=E[k]?l.getReserved(k):l.h[k],t.b+=d.string(k);else{if(b)throw new n(new x("Undefined entity: "+k,a,c));t.b+=d.string("&"+k+";")}k=c+1;q=p}else if(!(97<=l&&122>=l||65<=l&&90>=l||48<=l&&57>=l||58==l||46==l||95==l||45==l)&&35!=l){if(b)throw new n(new x("Invalid character in entity: "+String.fromCharCode(l),a,c));t.b+="&";l=c-k;t.b+=null==l?f.substr(a,
k,null):f.substr(a,k,l);k=c--;q=p}}l=a.charCodeAt(++c)}1==q&&(k=c,q=13);if(13==q){if(c!=k||0==H)b=c-k,t.b+=null==b?f.substr(a,k,null):f.substr(a,k,b),u.addChild(e.createPCData(t.b));return c}if(!b&&18==q&&13==p)return t.b+="&",b=c-k,t.b+=null==b?f.substr(a,k,null):f.substr(a,k,b),u.addChild(e.createPCData(t.b)),c;throw new n(new x("Unexpected end",a,c));};var n=function(a){Error.call(this);this.val=a;this.message=String(a);Error.captureStackTrace&&Error.captureStackTrace(this,n)};n.__name__=["js",
"_Boot","HaxeError"];n.wrap=function(a){return a instanceof Error?a:new n(a)};n.__super__=Error;n.prototype=v(Error.prototype,{__class__:n});var B=function(){};B.__name__=["js","Boot"];B.getClass=function(a){if(a instanceof Array&&null==a.__enum__)return Array;var b=a.__class__;if(null!=b)return b;a=B.__nativeClassName(a);return null!=a?B.__resolveNativeClass(a):null};B.__string_rec=function(a,b){if(null==a)return"null";if(5<=b.length)return"<...>";var c=typeof a;"function"==c&&(a.__name__||a.__ename__)&&
(c="object");switch(c){case "function":return"<function>";case "object":if(a instanceof Array){if(a.__enum__){if(2==a.length)return a[0];c=a[0]+"(";b+="\t";for(var e=2,f=a.length;e<f;){var d=e++;c=2!=d?c+(","+B.__string_rec(a[d],b)):c+B.__string_rec(a[d],b)}return c+")"}c=a.length;e="[";b+="\t";for(f=0;f<c;)d=f++,e+=(0<d?",":"")+B.__string_rec(a[d],b);return e+"]"}try{e=a.toString}catch(ea){return"???"}if(null!=e&&e!=Object.toString&&"function"==typeof e&&(c=a.toString(),"[object Object]"!=c))return c;
c=null;e="{\n";b+="\t";f=null!=a.hasOwnProperty;for(c in a)f&&!a.hasOwnProperty(c)||"prototype"==c||"__class__"==c||"__super__"==c||"__interfaces__"==c||"__properties__"==c||(2!=e.length&&(e+=", \n"),e+=b+c+" : "+B.__string_rec(a[c],b));b=b.substring(1);return e+("\n"+b+"}");case "string":return a;default:return String(a)}};B.__nativeClassName=function(a){a=B.__toStr.call(a).slice(8,-1);return"Object"==a||"Function"==a||"Math"==a||"JSON"==a?null:a};B.__resolveNativeClass=function(a){return r[a]};
var ca=require("child_process"),Z=require("fs"),da=require("path"),I=require("buffer").Buffer,y=function(){};y.__name__=["om","haxe","ErrorMessage"];y.parse=function(a){if(y.PATTERN.match(a)){a=new y;a.path=y.PATTERN.matched(1);a.line=d.parseInt(y.PATTERN.matched(2));switch(y.PATTERN.matched(3)){case "character":a.character=d.parseInt(y.PATTERN.matched(4));a.content=y.PATTERN.matched(7);break;case "characters":a.characters={start:d.parseInt(y.PATTERN.matched(4)),end:d.parseInt(y.PATTERN.matched(6))};
a.content=y.PATTERN.matched(7);break;case "lines":a.lines={start:d.parseInt(y.PATTERN.matched(4)),end:d.parseInt(y.PATTERN.matched(6))},a.content=y.PATTERN.matched(7)}return a}return null};y.prototype={__class__:y};var R=function(a,b){null==b&&(b=!1);null==a&&(a="haxe");this.haxePath=a;this.verbose=b};R.__name__=["om","haxe","LanguageServer"];R.prototype={start:function(a){var b=this;this.stop();this.buffer=new S;this.nextMessageLength=-1;this.process=ca.spawn(this.haxePath,["-v","--wait","stdio"]);
this.process.on("exit",A(this,this.handleExit));this.process.stderr.on("data",A(this,this.handleData));this.process.stdout.on("data",function(a){b.verbose&&window.console.debug("%c"+a.toString(),"color:#EA8220;")});a(null)},stop:function(){if(null!=this.process){this.process.removeAllListeners();try{this.process.kill()}catch(b){}this.process=null}for(var a=this.requestsHead;null!=a;)a.processResult(null),a=a.next;this.requestsHead=this.requestsTail=this.currentRequest=null},query:function(a,b,c,e,
f){a=new T(a,b,c,e,f);null==this.requestsHead?this.requestsHead=this.requestsTail=a:(this.requestsTail.next=a,a.prev=this.requestsTail,this.requestsTail=a);this.checkQueue()},checkQueue:function(){null==this.currentRequest&&null!=this.requestsHead&&(this.currentRequest=this.requestsHead,this.requestsHead=this.currentRequest.next,this.process.stdin.write(this.currentRequest.prepareBody()))},handleData:function(a){for(this.buffer.append(a);;){if(-1==this.nextMessageLength){a=this.buffer.tryReadLength();
if(-1==a)break;this.nextMessageLength=a}a=this.buffer.tryReadContent(this.nextMessageLength);if(null==a)break;this.nextMessageLength=-1;if(null!=this.currentRequest){var b=this.currentRequest;this.currentRequest=null;b.processResult(a);this.checkQueue()}}},handleExit:function(a,b){},__class__:R};var S=function(a){null==a&&(a=8192);this.size=a;this.buffer=new I(a);this.index=0};S.__name__=["om","haxe","_LanguageServer","MessageBuffer"];S.prototype={append:function(a){if(this.buffer.length-this.index>=
a.length)a.copy(this.buffer,this.index,0,a.length);else{var b=(Math.ceil((this.index+a.length)/this.size)+1)*this.size|0;0==this.index?(this.buffer=new I(b),a.copy(this.buffer,0,0,a.length)):this.buffer=I.concat([this.buffer.slice(0,this.index),a],b)}this.index+=a.length},tryReadLength:function(){if(4>this.index)return-1;var a=this.buffer.readInt32LE(0);this.buffer=this.buffer.slice(4);this.index-=4;return a},tryReadContent:function(a){if(this.index<a)return null;var b=this.buffer.toString("utf-8",
0,a);this.buffer.copy(this.buffer,0,a);this.index-=a;return b},__class__:S};var T=function(a,b,c,e,f){this.args=a;this.stdin=b;this.onResult=c;this.onError=e;this.onMessage=f};T.__name__=["om","haxe","_LanguageServer","Request"];T.prototype={prepareBody:function(){null!=this.stdin&&(this.args=this.args.concat(["-D","display-stdin"]));for(var a=new I(4),b=[a],c=0,e=0,f=this.args;e<f.length;){var d=f[e];++e;d=new I(""+d+"\n");b.push(d);c+=d.length}null!=this.stdin&&(e=new I([1]),b.push(e),f=new I(this.stdin),
b.push(f),c+=f.length+e.length);a.writeInt32LE(c,0);return I.concat(b,c+4)},processResult:function(a){if(null==a)this.onResult(null);else{var b="",c=!1,e=0;for(a=a.split("\n");e<a.length;){var f=a[e];++e;switch(f.charCodeAt(0)){case 1:f=p.replace(f.substring(1),"\u0001","\n");if(null!=this.onMessage)this.onMessage(f);break;case 2:c=!0;break;case 65:if(null!=this.onMessage)this.onMessage(f);break;default:b+=null==f?"null":""+f,b+="\n"}}b=p.trim(b);if(c)this.onError(b);else this.onResult(b)}},__class__:T};
var U=function(a){this.editor=a};U.__name__=["xxx","AutoComplete"];U.prototype={query:function(a,b,c,f,d){null==a&&(a=this.editor.getCursorBufferPosition());a=this.editor.getTextInBufferRange(new N(new Q(0,0),a));var g=a.length;g=""+this.editor.getPath()+"@"+g;null!=b&&(g+="@"+b);b=[h.hxml.getPath(),"--display",g];null!=c&&(b=b.concat(c));h.server.query(b,a,function(a){a=e.parse(a).firstElement();f(a)},function(a){null!=d&&d(a)},function(a){window.console.log(a)})},__class__:U};var C=function(a){null==
a&&(a=!0);this.suggestionPriority=2;this.disableForSelector=".source.haxe .comment, .source.hx .comment";this.selector=".source.haxe, .source.hx";a=atom.config.get("xxx.autocomplete").enabled;atom.config.observe("xxx.autocomplete",function(b){a=b.enabled})};C.__name__=["xxx","AutoCompleteProvider"];C.prototype={getSuggestions:function(a){var b=this;return new Promise(function(c,f){if(b.enabled&&null!=h.hxml){var d=a.editor;d.getCursorBufferPosition();f=a.bufferPosition;var g=a.prefix,u="",m=d.getTextInBufferRange(new N(new Q(f.row,
0),f));C.EXPR_PREFIX_FIELD.match(m)?(g=".",u=C.EXPR_PREFIX_FIELD.matched(1),f.column-=u.length):C.EXPR_PREFIX_CALL.match(m)&&(g="(",u=C.EXPR_PREFIX_CALL.matched(1),f.column-=u.length);d=new U(d);switch(g){case "(":d.query(f,null,null,function(a){if(a.nodeType!=e.Document&&a.nodeType!=e.Element)throw new n("Bad node type, expected Element or Document but found "+a.nodeType);a=a.children[0];if(a.nodeType==e.Document||a.nodeType==e.Element)throw new n("Bad node type, unexpected "+a.nodeType);a=p.trim(a.nodeValue).split("->");
a.pop();for(var b={type:"type",snippet:""},f=[],d=0,h=a.length;d<h;){var k=d++,g=p.trim(a[k]).split(" : ");f.push("${"+(k+1)+":"+g[0]+":"+g[1]+"}")}b.snippet=" "+f.join(", ")+" )$0";c([b])},function(a){});break;case ".":if(C.EXPR_ALPHANUMERIC_END.match(m)){c([]);break}if(C.EXPR_TYPEPATH.match(m)){var k=C.EXPR_TYPEPATH.matched(2);d.query(f,null,null,function(a){var b=[],f=[],d=[],h=[];for(a=a.elements();a.hasNext();){var g=a.next(),m=g.get("n");if(null==u||p.startsWith(m,u)){var q=g.get("k"),w=g.elementsNamed("d").next();
if(w.nodeType!=e.Document&&w.nodeType!=e.Element)throw new n("Bad node type, expected Element or Document but found "+w.nodeType);w=w.children[0];if(w.nodeType==e.Document||w.nodeType==e.Element)throw new n("Bad node type, unexpected "+w.nodeType);w=w.nodeValue;switch(q){case "method":q=m;g=g.elementsNamed("t").next();if(g.nodeType!=e.Document&&g.nodeType!=e.Element)throw new n("Bad node type, expected Element or Document but found "+g.nodeType);g=g.children[0];if(g.nodeType==e.Document||g.nodeType==
e.Element)throw new n("Bad node type, unexpected "+g.nodeType);g=p.htmlUnescape(g.nodeValue);m+="( "+g+" )";h.push({type:"method",text:q,displayText:m,description:w,leftLabel:"static"});break;case "package":f.push({type:q,text:m,description:w});break;case "type":g=k.split(".").pop().charAt(0);g.toUpperCase()!=g&&b.push({type:q,text:m,description:w});break;case "var":g=g.elementsNamed("t").next();if(g.nodeType!=e.Document&&g.nodeType!=e.Element)throw new n("Bad node type, expected Element or Document but found "+
g.nodeType);g=g.children[0];if(g.nodeType==e.Document||g.nodeType==e.Element)throw new n("Bad node type, unexpected "+g.nodeType);g=p.htmlUnescape(g.nodeValue);d.push({type:q,text:m,leftLabel:"static",rightLabel:g,description:w})}}}b=b.concat(f).concat(d).concat(h);c(b)},null)}else d.query(f,null,null,function(a){var f=[];for(a=a.elements();a.hasNext();){var d=a.next(),g=d.get("n");if(null==u||p.startsWith(g,u)){var h=d.get("k"),k=d.elementsNamed("d").next();if(k.nodeType!=e.Document&&k.nodeType!=
e.Element)throw new n("Bad node type, expected Element or Document but found "+k.nodeType);k=k.children[0];if(k.nodeType==e.Document||k.nodeType==e.Element)throw new n("Bad node type, unexpected "+k.nodeType);k=k.nodeValue;switch(h){case "method":d=d.elementsNamed("t").next();if(d.nodeType!=e.Document&&d.nodeType!=e.Element)throw new n("Bad node type, expected Element or Document but found "+d.nodeType);d=d.children[0];if(d.nodeType==e.Document||d.nodeType==e.Element)throw new n("Bad node type, unexpected "+
d.nodeType);g=b.getMethodSuggestion(g,d.nodeValue);g.description=k;f.push(g);break;case "package":f.push({type:"package",text:g,description:k});break;case "type":f.push({type:"type",text:g,description:k});break;case "var":d=d.elementsNamed("t").next();if(d.nodeType!=e.Document&&d.nodeType!=e.Element)throw new n("Bad node type, expected Element or Document but found "+d.nodeType);d=d.children[0];if(d.nodeType==e.Document||d.nodeType==e.Element)throw new n("Bad node type, unexpected "+d.nodeType);h=
d.nodeValue;f.push({type:"variable",text:g,displayText:g,rightLabel:h,description:k})}}}c(f)},function(a){});break;default:d.query(f,"toplevel",null,function(a){if(null==a)c([]);else{var b=[];for(a=a.elements();a.hasNext();){var d=a.next();if(d.nodeType!=e.Document&&d.nodeType!=e.Element)throw new n("Bad node type, expected Element or Document but found "+d.nodeType);var f=d.children[0];if(f.nodeType==e.Document||f.nodeType==e.Element)throw new n("Bad node type, unexpected "+f.nodeType);f=f.nodeValue;
if(!(0<g.length)||p.startsWith(f,g))switch(d=d.get("k"),d){case "literal":b.push({type:"keyword",text:f});break;case "local":b.push({type:d,text:f});break;case "package":b.push({type:d,text:f});break;case "static":b.push({type:"method",text:f});break;case "type":b.push({type:d,text:f})}}c(b)}},function(a){})}}else c([])})},onDidInsertSuggestion:function(a){},dispose:function(){},getMethodSuggestion:function(a,b){b=b.split(" -> ");var c=a;b.pop();if("Void"==b[0])c+="()$0",a+="()";else{c=[];for(var f=
0,d=b.length;f<d;){var e=f++,g=p.trim(b[e]).split(" : ");c.push("${"+(e+1)+":"+g[0]+":"+g[1]+"}")}c="( "+c.join(", ")+" )$0"}return{type:"method",snippet:c,displayText:a}},__class__:C};var O=function(a){P.call(this);this.hxml=a};O.__name__=["xxx","Build"];O.__super__=P;O.prototype=v(P.prototype,{start:function(a){null==a&&(a=!1);var b=this;this.args=["--cwd",this.hxml.getParent().getPath()];a&&this.args.push("-v");this.args.push(this.hxml.getBaseName());h.server.query(this.args,null,function(a){b.emit("end",
0)},function(a){a=p.trim(a);b.emit("error",a);b.emit("end",null)},function(a){b.emit("message",a)});this.emit("start",null)},__class__:O});var h=g.xxx.IDE=function(){};h.__name__=["xxx","IDE"];h.activate=function(a){h.disposables=new aa;h.emitter=new P;h.statusbar=new K;h.projectPaths=atom.project.getPaths();h.server=new R(atom.config.get("xxx.haxe_path"),!0);M.delay(function(){h.server.start(function(a){null!=a?atom.notifications.addWarning(a):h.disposables.add(atom.commands.add("atom-workspace",
"xxx:build",function(a){a=a.target.getAttribute("data-path");null!=a&&"hxml"==z.extension(a)&&null!=h.hxml&&a!=h.hxml.getPath()&&h.selectHxml(a);h.build()}))})},atom.config.get("xxx.haxe_server_startdelay"));h.searchHxmlFiles(null,null,function(b){h.hxmlFiles=b;null!=a&&null!=a.hxml?-1!=h.hxmlFiles.indexOf(a.hxml)&&h.selectHxml(a.hxml):h.selectHxml(b[0]);h.disposables.add(atom.project.onDidChangePaths(function(a){for(var b=[],c=0;c<a.length;){var f=a[c];++c;for(var d=!0,e=0,g=h.projectPaths;e<g.length;){var m=
g[e];++e;if(m==f){d=!1;break}}d&&b.push(f)}h.searchHxmlFiles(b,null,function(a){h.hxmlFiles=h.hxmlFiles.concat(a)});return h.projectPaths=a}));h.disposables.add(atom.workspace.observeTextEditors(function(a){a=a.getPath();null!=a&&z.extension(a)}))})};h.serialize=function(){return{hxml:null!=h.hxml?h.hxml.getPath():null}};h.deactivate=function(){h.disposables.dispose();h.server.stop()};h.getConfig=function(a){return atom.config.get("xxx."+a)};h.onSelectHxml=function(a){return h.emitter.on("hxml_select",
a)};h.onBuild=function(a){return h.emitter.on("build",a)};h.selectHxml=function(a){if(null==a)h.hxml=null;else{if(null!=h.hxml&&a==h.hxml.getPath())return;h.hxml=new X(a)}h.emitter.emit("hxml_select",h.hxml)};h.build=function(){if(null==h.hxml)return atom.notifications.addWarning("No hxml file selected"),null;var a=new O(h.hxml);new D(a);h.emitter.emit("build",a);a.start();return a};h.searchHxmlFiles=function(a,b,c){null==b&&(b=3);null==a&&(a=atom.project.getPaths());for(var f=function(a,c,d){null==
d&&(d=0);var e=[];Z.readdir(a,function(g,h){if(null!=g)c(e);else{var k=h.length;if(0==k)c(e);else for(g=0;g<h.length;){var l=[h[g]];++g;var m=da.resolve(a,l[0]);l[0]=m;Z.stat(l[0],function(a){return function(g,h){null!=h&&h.isDirectory()?d<b?(g=a[0],h=function(){return function(a){e=e.concat(a);0==--k&&c(e)}}(),f(g,h,d+1)):0==--k&&c(e):("hxml"==z.extension(a[0])&&"extraParams.hxml"!=z.withoutDirectory(a[0])&&e.push(a[0]),0==--k&&c(e))}}(l))}}})},d=[],e=0,g=0;g<a.length;){var h=a[g];++g;f(h,function(b){d=
d.concat(b);(e+=1)==a.length&&c(d)})}};h.consumeStatusBar=function(a){a.addLeftTile({item:h.statusbar.element,priority:-100})};h.provideAutoCompletion=function(){return new C};h.provideService=function(){return{getHxml:function(){return h.hxml},selectHxml:h.selectHxml,build:h.build}};var V=function(a,b){this.error=b;this.element=window.document.createElement("li");this.element.classList.add("message","error");var c=window.document.createElement("i");c.textContent=d.string(a+1);this.element.appendChild(c);
a=window.document.createElement("span");a.classList.add("path");a.textContent=b.path;this.element.appendChild(a);a=window.document.createElement("span");a.classList.add("line");a.textContent=null==b.line?"null":""+b.line;this.element.appendChild(a);null!=b.characters&&(a=window.document.createElement("span"),a.classList.add("start"),a.textContent=d.string(b.characters.start),this.element.appendChild(a),a=window.document.createElement("span"),a.classList.add("end"),a.textContent=d.string(b.characters.end),
this.element.appendChild(a));a=window.document.createElement("span");a.classList.add("content");a.textContent=b.content;this.element.appendChild(a)};V.__name__=["xxx","view","_BuildView","ErrorMessageView"];V.prototype={select:function(){},__class__:V};var D=function(a){var b=this;null!=D.current&&D.current.destroy();D.current=this;this.element=window.document.createElement("div");this.element.classList.add("xxx-build","resizer","native-key-bindings");this.element.setAttribute("tabindex","-1");this.messages=
window.document.createElement("ol");this.messages.classList.add("messages","scroller");this.element.appendChild(this.messages);this.panel=atom.workspace.addBottomPanel({item:this.element,visible:!0});var c=[];a.on("start",function(){var a=process.hrtime();b.timeStart=(1E9*a[0]+a[1])/1E6;c=[]});a.on("message",function(a){b.log(a)});a.on("error",function(a){for(var d=0,f=a.split("\n");d<f.length;){var e=f[d];++d;e=[y.parse(e)];if(null==e[0])b.log(a,"error");else{c.push(e[0]);var g=[new V(b.messages.children.length,
e[0])];g[0].element.onclick=function(a,b){return function(c){a[0].select();c.ctrlKey&&D.openErrorPosition(b[0])}}(g,e);b.messages.appendChild(g[0].element)}}});a.on("end",function(d){if(0==d)0==b.messages.children.length&&b.panel.hide();else if(0<c.length){d=c[0];var e=a.hxml.getPath(),f=z.directory(e)+"/"+d.path;(new X(f,!1)).existsSync()||(e=atom.project.relativizePath(e),d.path=e[0]+"/"+d.path)}});this.element.addEventListener("click",A(this,this.handleClick),!1)};D.__name__=["xxx","view","BuildView"];
D.openPosition=function(a,b,c,d,e,f){null==e&&(e=!0);null==d&&(d=!0);atom.workspace.open(a,{initialLine:b,initialColumn:c,activatePane:d,searchAllPanes:e}).then(function(a){null!=f&&f(a)})};D.openErrorPosition=function(a){var b=a.line-1;D.openPosition(a.path,b,a.character,null,null,function(c){null!=a.characters&&c.setSelectedBufferRange(new N(new Q(b,a.characters.start),new Q(b,a.characters.end)))})};D.prototype={destroy:function(){this.panel.destroy()},log:function(a,b){a=p.trim(a);if(0!=a.length){var c=
window.document.createElement("li");c.classList.add("message");null!=b&&c.classList.add(b);b=window.document.createElement("span");b.classList.add("time");var e=process.hrtime();b.textContent=d.string((1E9*e[0]+e[1])/1E6-this.timeStart|0);c.appendChild(b);b=window.document.createElement("span");b.classList.add("content");b.textContent=a;c.appendChild(b);this.messages.appendChild(c)}},handleClick:function(a){a.ctrlKey&&this.panel.hide()},__class__:D};var K=function(){var a=this;this.element=window.document.createElement("div");
this.element.classList.add("status-bar-xxx","inline-block");this.icon=window.document.createElement("span");this.icon.classList.add("icon-haxe");this.element.appendChild(this.icon);this.info=window.document.createElement("a");this.info.classList.add("info");this.element.appendChild(this.info);this.meta=window.document.createElement("span");this.meta.classList.add("meta");this.element.appendChild(this.meta);h.emitter.on("hxml_select",A(this,this.changeHxml));h.emitter.on("build",function(b){var c=
null,d=0;b.on("start",function(){var b=process.hrtime();c=(1E9*b[0]+b[1])/1E6;a.changeStatus("active")});b.on("message",function(a){});b.on("error",function(b){d+=1;a.changeStatus("error")});b.on("end",function(b){if(0==b){a.changeStatus("success");b=process.hrtime();b=((1E9*b[0]+b[1])/1E6-c)/1E3;b=null==b?"null":""+b;var e=b.indexOf(".");a.meta.textContent=b.substring(0,e)+b.substring(e,3)+"s"}else a.changeStatus("error"),a.meta.textContent="("+d+")"})});this.info.addEventListener("click",A(this,
this.handleClickInfo),!1)};K.__name__=["xxx","view","StatusbarView"];K.getRelativePath=function(a){a=atom.project.relativizePath(a);var b=a[0].split("/");return b[b.length-1]+"/"+a[1]};K.prototype={setMeta:function(a){this.meta.textContent=a},dispose:function(){this.info.removeEventListener("click",A(this,this.handleClickInfo));null!=this.contextMenu&&this.contextMenu.dispose()},changeHxml:function(a){null==a?(this.icon.style.display="none",this.info.textContent=""):(this.icon.style.display="inline-block",
a=K.getRelativePath(a.getPath()),this.info.textContent=z.withoutExtension(a));this.meta.textContent="";this.buildContextMenu()},changeStatus:function(a){a!=this.status&&(null!=this.status&&(this.icon.classList.remove(this.status),this.info.classList.remove(this.status)),this.status=a,null!=a&&(this.icon.classList.add(a),this.info.classList.add(a)))},buildContextMenu:function(){null!=this.contextMenu&&this.contextMenu.dispose();var a=[];null!=h.hxml&&(a.push({label:"Build",command:"xxx:build"}),a.push({type:"separator"}));
for(var b=0,c=h.hxmlFiles;b<c.length;){var d=c[b];++b;null!=h.hxml&&h.hxml.getPath()==d||a.push({label:K.getRelativePath(d),command:"xxx:select-hxml"})}this.contextMenu=atom.contextMenu.add({".status-bar-xxx .info":a})},handleClickInfo:function(a){a.ctrlKey?h.build():null!=h.hxml&&atom.workspace.open(h.hxml.getPath())},__class__:K};var ba=0;String.prototype.__class__=String;String.__name__=["String"];Array.__name__=["Array"];Date.prototype.__class__=Date;Date.__name__=["Date"];var E={};module.exports=
h;e.Element=0;e.PCData=1;e.CData=2;e.Comment=3;e.DocType=4;e.ProcessingInstruction=5;e.Document=6;F.escapes=function(a){a=new L;null!=E.lt?a.setReserved("lt","<"):a.h.lt="<";null!=E.gt?a.setReserved("gt",">"):a.h.gt=">";null!=E.amp?a.setReserved("amp","&"):a.h.amp="&";null!=E.quot?a.setReserved("quot",'"'):a.h.quot='"';null!=E.apos?a.setReserved("apos","'"):a.h.apos="'";return a}(this);B.__toStr={}.toString;y.PATTERN=new m("^\\s*(.+):([0-9]+):\\s*(characters*|lines)\\s([0-9]+)(-([0-9]+))?\\s:\\s(.+)$",
"i");C.EXPR_TYPEPATH=new m("(import|using)\\s+([a-zA-Z0-9_]+(?:\\.[a-zA-Z0-9_]+)*)(?:\\s+(?:in|as)\\s+([a-zA-Z0-9_]+))?","g");C.EXPR_ALPHANUMERIC_END=new m("[^a-zA-Z0-9_\\]\\)]([\\.0-9]+)$","");C.EXPR_PREFIX_FIELD=new m("\\.([a-zA-Z_][a-zA-Z_0-9]*)$","");C.EXPR_PREFIX_CALL=new m("\\(( *)$","");h.EVENT_SELECT_HXML="hxml_select";h.EVENT_BUILD="build"})("undefined"!=typeof exports?exports:"undefined"!=typeof window?window:"undefined"!=typeof self?self:this,"undefined"!=typeof window?window:"undefined"!=
typeof global?global:"undefined"!=typeof self?self:this);
