
import Atom.commands;
import Atom.notifications;
import Atom.workspace;
import atom.CompositeDisposable;
import atom.Directory;
import atom.Disposable;
import atom.Emitter;
import atom.File;
import atom.Panel;
import atom.Point;
import atom.Range;
import atom.TextBuffer;
import atom.TextEditor;
import haxe.Timer.delay;
import js.Browser.document;
import js.Browser.console;
import js.Promise;
import js.html.AnchorElement;
import js.html.DivElement;
import js.html.Element;
import js.html.LIElement;
import js.html.OListElement;
import js.html.SpanElement;
import js.node.Fs;
import om.Time;

using StringTools;
using haxe.io.Path;
